/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET[\'appKey\']);$b = htmlspecialchars($_GET[\'appRestKey\']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NameStringValueResponse } from './nameStringValueResponse';

export class AchievementShortResponse {
    'valid'?: boolean;
    'message'?: string;
    'version'?: number;
    'serializeNulls'?: boolean;
    'startTimeLog'?: number;
    'errorCode'?: string;
    'request'?: Array<NameStringValueResponse>;
    'achievementId'?: number;
    'title'?: string;
    'description'?: string;
    'analyticsTag'?: string;
    'rankType'?: string;
    'rankIncrement'?: number;
    'validate'?: boolean;
    'appName'?: string;
    'active'?: boolean;
    'updated'?: number;
    'created'?: number;
    'tierCount'?: number;
    'minIncrement'?: number;
    'maxIncrement'?: number;
    'returning'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "serializeNulls",
            "baseName": "serializeNulls",
            "type": "boolean"
        },
        {
            "name": "startTimeLog",
            "baseName": "startTimeLog",
            "type": "number"
        },
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "Array<NameStringValueResponse>"
        },
        {
            "name": "achievementId",
            "baseName": "achievementId",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "analyticsTag",
            "baseName": "analyticsTag",
            "type": "string"
        },
        {
            "name": "rankType",
            "baseName": "rankType",
            "type": "string"
        },
        {
            "name": "rankIncrement",
            "baseName": "rankIncrement",
            "type": "number"
        },
        {
            "name": "validate",
            "baseName": "validate",
            "type": "boolean"
        },
        {
            "name": "appName",
            "baseName": "appName",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "tierCount",
            "baseName": "tierCount",
            "type": "number"
        },
        {
            "name": "minIncrement",
            "baseName": "minIncrement",
            "type": "number"
        },
        {
            "name": "maxIncrement",
            "baseName": "maxIncrement",
            "type": "number"
        },
        {
            "name": "returning",
            "baseName": "returning",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AchievementShortResponse.attributeTypeMap;
    }
}

