/**
 * Sirqul IoT Platform
 *
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPermissionsListResponse } from './userPermissionsListResponse';
import { ScoreListResponse } from './scoreListResponse';
import { AssetShortResponse } from './assetShortResponse';
import { AccountShortResponse } from './accountShortResponse';
import { TicketListResponse } from './ticketListResponse';
import { GameLevelListResponse } from './gameLevelListResponse';
import { ApplicationShortResponse } from './applicationShortResponse';
import { NameStringValueResponse } from './nameStringValueResponse';


export interface PackResponse { 
    action?: PackResponse.ActionEnum;
    highestAppVersion?: string;
    gameType?: string;
    packId?: number;
    name?: string;
    description?: string;
    active?: boolean;
    downloaded?: boolean;
    completed?: boolean;
    icon?: AssetShortResponse;
    background?: AssetShortResponse;
    ticketsEarned?: number;
    levels?: GameLevelListResponse;
    sequenceType?: string;
    scores?: ScoreListResponse;
    owner?: AccountShortResponse;
    costToRedeem?: number;
    price?: number;
    priceType?: string;
    userPermissionsList?: UserPermissionsListResponse;
    results?: Array<NameStringValueResponse>;
    tickets?: TicketListResponse;
    authorOverride?: string;
    updatedDate?: number;
    startDate?: number;
    endDate?: number;
    packType?: PackResponse.PackTypeEnum;
    packOrder?: number;
    appKey?: string;
    application?: ApplicationShortResponse;
    inGame?: boolean;
    highest?: boolean;
    allocateTickets?: boolean;
    ticketType?: string;
    ticketCount?: number;
    points?: number;
}
export namespace PackResponse {
    export const ActionEnum = {
        Data: 'DATA',
        Save: 'SAVE',
        Delete: 'DELETE',
        Get: 'GET'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
    export const PackTypeEnum = {
        Tutorial: 'TUTORIAL',
        Builtin: 'BUILTIN',
        Download: 'DOWNLOAD',
        Threshold: 'THRESHOLD',
        Theme: 'THEME',
        Tournament: 'TOURNAMENT'
    } as const;
    export type PackTypeEnum = typeof PackTypeEnum[keyof typeof PackTypeEnum];
}


