/**
 * Sirqul IoT Platform
 *
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectionInfoResponse } from './connectionInfoResponse';
import { ProfileInfoResponse } from './profileInfoResponse';
import { AppInfoResponse } from './appInfoResponse';
import { NameStringValueResponse } from './nameStringValueResponse';


export interface ProfileResponse { 
    valid?: boolean;
    message?: string;
    version?: number;
    serializeNulls?: boolean;
    startTimeLog?: number;
    errorCode?: string;
    request?: Array<NameStringValueResponse>;
    loginAccountId?: number;
    validated?: boolean;
    appInfo?: AppInfoResponse;
    canViewAppInfo?: boolean;
    canViewFriendInfo?: boolean;
    canViewProfileInfo?: boolean;
    flagCount?: number;
    friendInfo?: ConnectionInfoResponse;
    isBlocked?: boolean;
    isProfileOwner?: boolean;
    metFlagThreshold?: boolean;
    profileInfo?: ProfileInfoResponse;
    trusted?: boolean;
    following?: boolean;
    friendRequested?: boolean;
    friendRequestPending?: boolean;
    blocked?: boolean;
    flagged?: boolean;
    profileOwner?: boolean;
    friend?: boolean;
    returning?: string;
}

