/**
 * Sirqul IoT Platform
 *
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreListResponse } from './scoreListResponse';
import { AssetShortResponse } from './assetShortResponse';


export interface WordzWordResponse { 
    id?: number;
    word?: string;
    definition?: string;
    scores?: ScoreListResponse;
    icon?: AssetShortResponse;
    image?: AssetShortResponse;
    authorOverride?: string;
    updatedDate?: number;
    startDate?: number;
    endDate?: number;
    createdDate?: number;
    active?: boolean;
    allocateTickets?: boolean;
    ticketType?: string;
    ticketCount?: number;
    points?: number;
}

