/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.BidResponse
import org.openapitools.client.models.SirqulResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class BidApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://dev.sirqul.com/api/3.18")
        }
    }

    /**
     * POST /bid/create
     * Create Bid
     * Creates a bid on a biddable object
     * @param biddableType A biddable object type. Possible values include: CREATIVE (ads).
     * @param biddableId The id of the biddable object
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression.
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click.
     * @param budgetAmount The allocated budget amount that will be used
     * @param budgetSchedule The schedule for when the allocated budget amount is reset
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return BidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBid(biddableType: kotlin.String, biddableId: kotlin.Long, amountPerView: kotlin.Double, amountPerAction: kotlin.Double, budgetAmount: kotlin.Double, budgetSchedule: kotlin.String, deviceId: kotlin.String? = null, accountId: kotlin.Long? = null) : BidResponse {
        val localVarResponse = createBidWithHttpInfo(biddableType = biddableType, biddableId = biddableId, amountPerView = amountPerView, amountPerAction = amountPerAction, budgetAmount = budgetAmount, budgetSchedule = budgetSchedule, deviceId = deviceId, accountId = accountId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /bid/create
     * Create Bid
     * Creates a bid on a biddable object
     * @param biddableType A biddable object type. Possible values include: CREATIVE (ads).
     * @param biddableId The id of the biddable object
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression.
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click.
     * @param budgetAmount The allocated budget amount that will be used
     * @param budgetSchedule The schedule for when the allocated budget amount is reset
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return ApiResponse<BidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBidWithHttpInfo(biddableType: kotlin.String, biddableId: kotlin.Long, amountPerView: kotlin.Double, amountPerAction: kotlin.Double, budgetAmount: kotlin.Double, budgetSchedule: kotlin.String, deviceId: kotlin.String?, accountId: kotlin.Long?) : ApiResponse<BidResponse?> {
        val localVariableConfig = createBidRequestConfig(biddableType = biddableType, biddableId = biddableId, amountPerView = amountPerView, amountPerAction = amountPerAction, budgetAmount = budgetAmount, budgetSchedule = budgetSchedule, deviceId = deviceId, accountId = accountId)

        return request<Unit, BidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createBid
     *
     * @param biddableType A biddable object type. Possible values include: CREATIVE (ads).
     * @param biddableId The id of the biddable object
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression.
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click.
     * @param budgetAmount The allocated budget amount that will be used
     * @param budgetSchedule The schedule for when the allocated budget amount is reset
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return RequestConfig
     */
    fun createBidRequestConfig(biddableType: kotlin.String, biddableId: kotlin.Long, amountPerView: kotlin.Double, amountPerAction: kotlin.Double, budgetAmount: kotlin.Double, budgetSchedule: kotlin.String, deviceId: kotlin.String?, accountId: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (deviceId != null) {
                    put("deviceId", listOf(deviceId.toString()))
                }
                if (accountId != null) {
                    put("accountId", listOf(accountId.toString()))
                }
                put("biddableType", listOf(biddableType.toString()))
                put("biddableId", listOf(biddableId.toString()))
                put("amountPerView", listOf(amountPerView.toString()))
                put("amountPerAction", listOf(amountPerAction.toString()))
                put("budgetAmount", listOf(budgetAmount.toString()))
                put("budgetSchedule", listOf(budgetSchedule.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/bid/create",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /bid/delete
     * Delete Bid
     * Deleted a bid on a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return SirqulResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteBid(bidId: kotlin.Long, deviceId: kotlin.String? = null, accountId: kotlin.Long? = null) : SirqulResponse {
        val localVarResponse = deleteBidWithHttpInfo(bidId = bidId, deviceId = deviceId, accountId = accountId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SirqulResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /bid/delete
     * Delete Bid
     * Deleted a bid on a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return ApiResponse<SirqulResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteBidWithHttpInfo(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?) : ApiResponse<SirqulResponse?> {
        val localVariableConfig = deleteBidRequestConfig(bidId = bidId, deviceId = deviceId, accountId = accountId)

        return request<Unit, SirqulResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteBid
     *
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return RequestConfig
     */
    fun deleteBidRequestConfig(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (deviceId != null) {
                    put("deviceId", listOf(deviceId.toString()))
                }
                if (accountId != null) {
                    put("accountId", listOf(accountId.toString()))
                }
                put("bidId", listOf(bidId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/bid/delete",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /bid/get
     * Get Bid
     * Get the bid details of a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return BidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getBid(bidId: kotlin.Long, deviceId: kotlin.String? = null, accountId: kotlin.Long? = null) : BidResponse {
        val localVarResponse = getBidWithHttpInfo(bidId = bidId, deviceId = deviceId, accountId = accountId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /bid/get
     * Get Bid
     * Get the bid details of a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return ApiResponse<BidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getBidWithHttpInfo(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?) : ApiResponse<BidResponse?> {
        val localVariableConfig = getBidRequestConfig(bidId = bidId, deviceId = deviceId, accountId = accountId)

        return request<Unit, BidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getBid
     *
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @return RequestConfig
     */
    fun getBidRequestConfig(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (deviceId != null) {
                    put("deviceId", listOf(deviceId.toString()))
                }
                if (accountId != null) {
                    put("accountId", listOf(accountId.toString()))
                }
                put("bidId", listOf(bidId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/bid/get",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /bid/update
     * Update Bid
     * Updates a bid on a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression. (optional)
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click. (optional)
     * @param budgetAmount The allocated budget amount that will be used (optional)
     * @param budgetSchedule The schedule for when the allocated budget amount is reset (optional)
     * @return BidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateBid(bidId: kotlin.Long, deviceId: kotlin.String? = null, accountId: kotlin.Long? = null, amountPerView: kotlin.Double? = null, amountPerAction: kotlin.Double? = null, budgetAmount: kotlin.Double? = null, budgetSchedule: kotlin.String? = null) : BidResponse {
        val localVarResponse = updateBidWithHttpInfo(bidId = bidId, deviceId = deviceId, accountId = accountId, amountPerView = amountPerView, amountPerAction = amountPerAction, budgetAmount = budgetAmount, budgetSchedule = budgetSchedule)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /bid/update
     * Update Bid
     * Updates a bid on a biddable object
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression. (optional)
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click. (optional)
     * @param budgetAmount The allocated budget amount that will be used (optional)
     * @param budgetSchedule The schedule for when the allocated budget amount is reset (optional)
     * @return ApiResponse<BidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateBidWithHttpInfo(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?, amountPerView: kotlin.Double?, amountPerAction: kotlin.Double?, budgetAmount: kotlin.Double?, budgetSchedule: kotlin.String?) : ApiResponse<BidResponse?> {
        val localVariableConfig = updateBidRequestConfig(bidId = bidId, deviceId = deviceId, accountId = accountId, amountPerView = amountPerView, amountPerAction = amountPerAction, budgetAmount = budgetAmount, budgetSchedule = budgetSchedule)

        return request<Unit, BidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateBid
     *
     * @param bidId The bid id
     * @param deviceId The device id (deviceId or accountId required) (optional)
     * @param accountId The account id of the user (deviceId or accountId required) (optional)
     * @param amountPerView The bid amount for views. For ads, this is the amount that will be taken for each impression. (optional)
     * @param amountPerAction The bid amount for actions. For ads, this is the amount that will be taken for each click. (optional)
     * @param budgetAmount The allocated budget amount that will be used (optional)
     * @param budgetSchedule The schedule for when the allocated budget amount is reset (optional)
     * @return RequestConfig
     */
    fun updateBidRequestConfig(bidId: kotlin.Long, deviceId: kotlin.String?, accountId: kotlin.Long?, amountPerView: kotlin.Double?, amountPerAction: kotlin.Double?, budgetAmount: kotlin.Double?, budgetSchedule: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (deviceId != null) {
                    put("deviceId", listOf(deviceId.toString()))
                }
                if (accountId != null) {
                    put("accountId", listOf(accountId.toString()))
                }
                put("bidId", listOf(bidId.toString()))
                if (amountPerView != null) {
                    put("amountPerView", listOf(amountPerView.toString()))
                }
                if (amountPerAction != null) {
                    put("amountPerAction", listOf(amountPerAction.toString()))
                }
                if (budgetAmount != null) {
                    put("budgetAmount", listOf(budgetAmount.toString()))
                }
                if (budgetSchedule != null) {
                    put("budgetSchedule", listOf(budgetSchedule.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/bid/update",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
