export * from './aMQPApi';
import { AMQPApi } from './aMQPApi';
export * from './accountApi';
import { AccountApi } from './accountApi';
export * from './achievementApi';
import { AchievementApi } from './achievementApi';
export * from './activityApi';
import { ActivityApi } from './activityApi';
export * from './albumApi';
import { AlbumApi } from './albumApi';
export * from './analyticsApi';
import { AnalyticsApi } from './analyticsApi';
export * from './appDataApi';
import { AppDataApi } from './appDataApi';
export * from './applicationApi';
import { ApplicationApi } from './applicationApi';
export * from './applicationConfigApi';
import { ApplicationConfigApi } from './applicationConfigApi';
export * from './assetApi';
import { AssetApi } from './assetApi';
export * from './assignmentApi';
import { AssignmentApi } from './assignmentApi';
export * from './audienceApi';
import { AudienceApi } from './audienceApi';
export * from './bidApi';
import { BidApi } from './bidApi';
export * from './billableEntityApi';
import { BillableEntityApi } from './billableEntityApi';
export * from './billingInfoApi';
import { BillingInfoApi } from './billingInfoApi';
export * from './cSVImportApi';
import { CSVImportApi } from './cSVImportApi';
export * from './cargoTypeApi';
import { CargoTypeApi } from './cargoTypeApi';
export * from './carrierApi';
import { CarrierApi } from './carrierApi';
export * from './categoryApi';
import { CategoryApi } from './categoryApi';
export * from './connectionApi';
import { ConnectionApi } from './connectionApi';
export * from './contestApi';
import { ContestApi } from './contestApi';
export * from './creativeApi';
import { CreativeApi } from './creativeApi';
export * from './dependentApi';
import { DependentApi } from './dependentApi';
export * from './disbursementApi';
import { DisbursementApi } from './disbursementApi';
export * from './employeeApi';
import { EmployeeApi } from './employeeApi';
export * from './eventApi';
import { EventApi } from './eventApi';
export * from './facebookApi';
import { FacebookApi } from './facebookApi';
export * from './favoriteApi';
import { FavoriteApi } from './favoriteApi';
export * from './filterApi';
import { FilterApi } from './filterApi';
export * from './flagApi';
import { FlagApi } from './flagApi';
export * from './gameApi';
import { GameApi } from './gameApi';
export * from './gameLevelApi';
import { GameLevelApi } from './gameLevelApi';
export * from './inviteApi';
import { InviteApi } from './inviteApi';
export * from './leaderboardApi';
import { LeaderboardApi } from './leaderboardApi';
export * from './likeApi';
import { LikeApi } from './likeApi';
export * from './listingApi';
import { ListingApi } from './listingApi';
export * from './locationApi';
import { LocationApi } from './locationApi';
export * from './locationApiV2Api';
import { LocationApiV2Api } from './locationApiV2Api';
export * from './mediaApi';
import { MediaApi } from './mediaApi';
export * from './missionApi';
import { MissionApi } from './missionApi';
export * from './missionInviteApi';
import { MissionInviteApi } from './missionInviteApi';
export * from './noteApi';
import { NoteApi } from './noteApi';
export * from './notificationApi';
import { NotificationApi } from './notificationApi';
export * from './objectStoreApi';
import { ObjectStoreApi } from './objectStoreApi';
export * from './offerApi';
import { OfferApi } from './offerApi';
export * from './offerStatusApi';
import { OfferStatusApi } from './offerStatusApi';
export * from './openAIApi';
import { OpenAIApi } from './openAIApi';
export * from './optimizeApi';
import { OptimizeApi } from './optimizeApi';
export * from './orsonApi';
import { OrsonApi } from './orsonApi';
export * from './packApi';
import { PackApi } from './packApi';
export * from './participantsApi';
import { ParticipantsApi } from './participantsApi';
export * from './pathingApi';
import { PathingApi } from './pathingApi';
export * from './postalCodeApi';
import { PostalCodeApi } from './postalCodeApi';
export * from './previewPersonaApi';
import { PreviewPersonaApi } from './previewPersonaApi';
export * from './programApi';
import { ProgramApi } from './programApi';
export * from './purchaseItemApi';
import { PurchaseItemApi } from './purchaseItemApi';
export * from './purchaseOrderApi';
import { PurchaseOrderApi } from './purchaseOrderApi';
export * from './questionApi';
import { QuestionApi } from './questionApi';
export * from './rankingApi';
import { RankingApi } from './rankingApi';
export * from './ratingApi';
import { RatingApi } from './ratingApi';
export * from './regionApi';
import { RegionApi } from './regionApi';
export * from './reportingApi';
import { ReportingApi } from './reportingApi';
export * from './reservationApi';
import { ReservationApi } from './reservationApi';
export * from './retailerApi';
import { RetailerApi } from './retailerApi';
export * from './retailerLocationApi';
import { RetailerLocationApi } from './retailerLocationApi';
export * from './retailerV2Api';
import { RetailerV2Api } from './retailerV2Api';
export * from './routeApi';
import { RouteApi } from './routeApi';
export * from './routeSettingApi';
import { RouteSettingApi } from './routeSettingApi';
export * from './routingApi';
import { RoutingApi } from './routingApi';
export * from './scheduledNotificationApi';
import { ScheduledNotificationApi } from './scheduledNotificationApi';
export * from './scoreApi';
import { ScoreApi } from './scoreApi';
export * from './secureAppApi';
import { SecureAppApi } from './secureAppApi';
export * from './serviceHubApi';
import { ServiceHubApi } from './serviceHubApi';
export * from './shipmentApi';
import { ShipmentApi } from './shipmentApi';
export * from './shipmentBatchApi';
import { ShipmentBatchApi } from './shipmentBatchApi';
export * from './simulationApi';
import { SimulationApi } from './simulationApi';
export * from './stopApi';
import { StopApi } from './stopApi';
export * from './stripeApi';
import { StripeApi } from './stripeApi';
export * from './subscriptionApi';
import { SubscriptionApi } from './subscriptionApi';
export * from './taskApi';
import { TaskApi } from './taskApi';
export * from './territoryApi';
import { TerritoryApi } from './territoryApi';
export * from './themeDescriptorApi';
import { ThemeDescriptorApi } from './themeDescriptorApi';
export * from './thirdPartyCredentialsApi';
import { ThirdPartyCredentialsApi } from './thirdPartyCredentialsApi';
export * from './ticketApi';
import { TicketApi } from './ticketApi';
export * from './tournamentApi';
import { TournamentApi } from './tournamentApi';
export * from './trackingApi';
import { TrackingApi } from './trackingApi';
export * from './triggerApi';
import { TriggerApi } from './triggerApi';
export * from './tripApi';
import { TripApi } from './tripApi';
export * from './twilioApi';
import { TwilioApi } from './twilioApi';
export * from './twitterApi';
import { TwitterApi } from './twitterApi';
export * from './userPermissionsApi';
import { UserPermissionsApi } from './userPermissionsApi';
export * from './vatomApi';
import { VatomApi } from './vatomApi';
export * from './vehicleApi';
import { VehicleApi } from './vehicleApi';
export * from './vehicleTypeApi';
import { VehicleTypeApi } from './vehicleTypeApi';
export * from './walletApi';
import { WalletApi } from './walletApi';
export * from './weatherApi';
import { WeatherApi } from './weatherApi';
export * from './wordApi';
import { WordApi } from './wordApi';
export * from './workflowApi';
import { WorkflowApi } from './workflowApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [AMQPApi, AccountApi, AchievementApi, ActivityApi, AlbumApi, AnalyticsApi, AppDataApi, ApplicationApi, ApplicationConfigApi, AssetApi, AssignmentApi, AudienceApi, BidApi, BillableEntityApi, BillingInfoApi, CSVImportApi, CargoTypeApi, CarrierApi, CategoryApi, ConnectionApi, ContestApi, CreativeApi, DependentApi, DisbursementApi, EmployeeApi, EventApi, FacebookApi, FavoriteApi, FilterApi, FlagApi, GameApi, GameLevelApi, InviteApi, LeaderboardApi, LikeApi, ListingApi, LocationApi, LocationApiV2Api, MediaApi, MissionApi, MissionInviteApi, NoteApi, NotificationApi, ObjectStoreApi, OfferApi, OfferStatusApi, OpenAIApi, OptimizeApi, OrsonApi, PackApi, ParticipantsApi, PathingApi, PostalCodeApi, PreviewPersonaApi, ProgramApi, PurchaseItemApi, PurchaseOrderApi, QuestionApi, RankingApi, RatingApi, RegionApi, ReportingApi, ReservationApi, RetailerApi, RetailerLocationApi, RetailerV2Api, RouteApi, RouteSettingApi, RoutingApi, ScheduledNotificationApi, ScoreApi, SecureAppApi, ServiceHubApi, ShipmentApi, ShipmentBatchApi, SimulationApi, StopApi, StripeApi, SubscriptionApi, TaskApi, TerritoryApi, ThemeDescriptorApi, ThirdPartyCredentialsApi, TicketApi, TournamentApi, TrackingApi, TriggerApi, TripApi, TwilioApi, TwitterApi, UserPermissionsApi, VatomApi, VehicleApi, VehicleTypeApi, WalletApi, WeatherApi, WordApi, WorkflowApi];
