/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MissionTask.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MissionTask_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MissionTask_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  MissionTask
    : public ModelBase
{
public:
    MissionTask();
    virtual ~MissionTask();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MissionTask members

    enum class TaskTypeEnum
    {
        PHOTO,
        VOTE,
        ASK,
        ANSWER,
        GROUP,
        INVITE,
        OFFER,
        AD,
        CUSTOM,
        GAME,
    };

    TaskTypeEnum toTaskTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromTaskTypeEnum(const TaskTypeEnum value) const;


    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int64_t value);

    bool isActive() const;
    bool activeIsSet() const;
    void unsetActive();
    void setActive(bool value);

    bool isValid() const;
    bool validIsSet() const;
    void unsetValid();
    void setValid(bool value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    utility::string_t getFormat() const;
    bool formatIsSet() const;
    void unsetFormat();
    void setFormat(const utility::string_t& value);

    utility::string_t getSuffix() const;
    bool suffixIsSet() const;
    void unsetSuffix();
    void setSuffix(const utility::string_t& value);

    TaskTypeEnum getTaskType() const;
    bool taskTypeIsSet() const;
    void unsetTaskType();
    void setTaskType(const TaskTypeEnum value);


protected:
    int64_t m_Id;
    bool m_IdIsSet;

    bool m_Active;
    bool m_ActiveIsSet;

    bool m_Valid;
    bool m_ValidIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    utility::string_t m_Format;
    bool m_FormatIsSet;

    utility::string_t m_Suffix;
    bool m_SuffixIsSet;

    TaskTypeEnum m_TaskType;
    bool m_TaskTypeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MissionTask_H_ */
