/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * VehicleCargoSetting.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_VehicleCargoSetting_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_VehicleCargoSetting_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/CargoType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class CargoType;


class  VehicleCargoSetting
    : public ModelBase
{
public:
    VehicleCargoSetting();
    virtual ~VehicleCargoSetting();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// VehicleCargoSetting members


    bool isValid() const;
    bool validIsSet() const;
    void unsetValid();
    void setValid(bool value);

    std::shared_ptr<CargoType> getCargoType() const;
    bool cargoTypeIsSet() const;
    void unsetCargoType();
    void setCargoType(const std::shared_ptr<CargoType>& value);

    int32_t getMaxUnit() const;
    bool maxUnitIsSet() const;
    void unsetMaxUnit();
    void setMaxUnit(int32_t value);


protected:
    bool m_Valid;
    bool m_ValidIsSet;

    std::shared_ptr<CargoType> m_CargoType;
    bool m_CargoTypeIsSet;

    int32_t m_MaxUnit;
    bool m_MaxUnitIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_VehicleCargoSetting_H_ */
