/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountShortResponse
import org.openapitools.client.models.OfferShortResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reservationId 
 * @param reservableId 
 * @param reservableType 
 * @param account 
 * @param createdDate 
 * @param updatedDate 
 * @param startDate 
 * @param endDate 
 * @param transaction 
 */


data class ReservationResponse (

    @Json(name = "reservationId")
    val reservationId: kotlin.Long? = null,

    @Json(name = "reservableId")
    val reservableId: kotlin.Long? = null,

    @Json(name = "reservableType")
    val reservableType: kotlin.String? = null,

    @Json(name = "account")
    val account: AccountShortResponse? = null,

    @Json(name = "createdDate")
    val createdDate: kotlin.Long? = null,

    @Json(name = "updatedDate")
    val updatedDate: kotlin.Long? = null,

    @Json(name = "startDate")
    val startDate: kotlin.Long? = null,

    @Json(name = "endDate")
    val endDate: kotlin.Long? = null,

    @Json(name = "transaction")
    val transaction: OfferShortResponse? = null

) {


}

