export * from './aMQP.service';
import { AMQPService } from './aMQP.service';
export * from './account.service';
import { AccountService } from './account.service';
export * from './achievement.service';
import { AchievementService } from './achievement.service';
export * from './activity.service';
import { ActivityService } from './activity.service';
export * from './album.service';
import { AlbumService } from './album.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './appData.service';
import { AppDataService } from './appData.service';
export * from './application.service';
import { ApplicationService } from './application.service';
export * from './applicationConfig.service';
import { ApplicationConfigService } from './applicationConfig.service';
export * from './asset.service';
import { AssetService } from './asset.service';
export * from './assignment.service';
import { AssignmentService } from './assignment.service';
export * from './audience.service';
import { AudienceService } from './audience.service';
export * from './bid.service';
import { BidService } from './bid.service';
export * from './billableEntity.service';
import { BillableEntityService } from './billableEntity.service';
export * from './billingInfo.service';
import { BillingInfoService } from './billingInfo.service';
export * from './cSVImport.service';
import { CSVImportService } from './cSVImport.service';
export * from './cargoType.service';
import { CargoTypeService } from './cargoType.service';
export * from './carrier.service';
import { CarrierService } from './carrier.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './connection.service';
import { ConnectionService } from './connection.service';
export * from './contest.service';
import { ContestService } from './contest.service';
export * from './creative.service';
import { CreativeService } from './creative.service';
export * from './dependent.service';
import { DependentService } from './dependent.service';
export * from './disbursement.service';
import { DisbursementService } from './disbursement.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './event.service';
import { EventService } from './event.service';
export * from './facebook.service';
import { FacebookService } from './facebook.service';
export * from './favorite.service';
import { FavoriteService } from './favorite.service';
export * from './filter.service';
import { FilterService } from './filter.service';
export * from './flag.service';
import { FlagService } from './flag.service';
export * from './game.service';
import { GameService } from './game.service';
export * from './gameLevel.service';
import { GameLevelService } from './gameLevel.service';
export * from './invite.service';
import { InviteService } from './invite.service';
export * from './leaderboard.service';
import { LeaderboardService } from './leaderboard.service';
export * from './like.service';
import { LikeService } from './like.service';
export * from './listing.service';
import { ListingService } from './listing.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './locationApiV2.service';
import { LocationApiV2Service } from './locationApiV2.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './mission.service';
import { MissionService } from './mission.service';
export * from './missionInvite.service';
import { MissionInviteService } from './missionInvite.service';
export * from './note.service';
import { NoteService } from './note.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './objectStore.service';
import { ObjectStoreService } from './objectStore.service';
export * from './offer.service';
import { OfferService } from './offer.service';
export * from './offerStatus.service';
import { OfferStatusService } from './offerStatus.service';
export * from './openAI.service';
import { OpenAIService } from './openAI.service';
export * from './optimize.service';
import { OptimizeService } from './optimize.service';
export * from './orson.service';
import { OrsonService } from './orson.service';
export * from './pack.service';
import { PackService } from './pack.service';
export * from './participants.service';
import { ParticipantsService } from './participants.service';
export * from './pathing.service';
import { PathingService } from './pathing.service';
export * from './postalCode.service';
import { PostalCodeService } from './postalCode.service';
export * from './previewPersona.service';
import { PreviewPersonaService } from './previewPersona.service';
export * from './program.service';
import { ProgramService } from './program.service';
export * from './purchaseItem.service';
import { PurchaseItemService } from './purchaseItem.service';
export * from './purchaseOrder.service';
import { PurchaseOrderService } from './purchaseOrder.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './ranking.service';
import { RankingService } from './ranking.service';
export * from './rating.service';
import { RatingService } from './rating.service';
export * from './region.service';
import { RegionService } from './region.service';
export * from './reporting.service';
import { ReportingService } from './reporting.service';
export * from './reservation.service';
import { ReservationService } from './reservation.service';
export * from './retailer.service';
import { RetailerService } from './retailer.service';
export * from './retailerLocation.service';
import { RetailerLocationService } from './retailerLocation.service';
export * from './retailerV2.service';
import { RetailerV2Service } from './retailerV2.service';
export * from './route.service';
import { RouteService } from './route.service';
export * from './routeSetting.service';
import { RouteSettingService } from './routeSetting.service';
export * from './routing.service';
import { RoutingService } from './routing.service';
export * from './scheduledNotification.service';
import { ScheduledNotificationService } from './scheduledNotification.service';
export * from './score.service';
import { ScoreService } from './score.service';
export * from './secureApp.service';
import { SecureAppService } from './secureApp.service';
export * from './serviceHub.service';
import { ServiceHubService } from './serviceHub.service';
export * from './shipment.service';
import { ShipmentService } from './shipment.service';
export * from './shipmentBatch.service';
import { ShipmentBatchService } from './shipmentBatch.service';
export * from './simulation.service';
import { SimulationService } from './simulation.service';
export * from './stop.service';
import { StopService } from './stop.service';
export * from './stripe.service';
import { StripeService } from './stripe.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './territory.service';
import { TerritoryService } from './territory.service';
export * from './themeDescriptor.service';
import { ThemeDescriptorService } from './themeDescriptor.service';
export * from './thirdPartyCredentials.service';
import { ThirdPartyCredentialsService } from './thirdPartyCredentials.service';
export * from './ticket.service';
import { TicketService } from './ticket.service';
export * from './tournament.service';
import { TournamentService } from './tournament.service';
export * from './tracking.service';
import { TrackingService } from './tracking.service';
export * from './trigger.service';
import { TriggerService } from './trigger.service';
export * from './trip.service';
import { TripService } from './trip.service';
export * from './twilio.service';
import { TwilioService } from './twilio.service';
export * from './twitter.service';
import { TwitterService } from './twitter.service';
export * from './userPermissions.service';
import { UserPermissionsService } from './userPermissions.service';
export * from './vatom.service';
import { VatomService } from './vatom.service';
export * from './vehicle.service';
import { VehicleService } from './vehicle.service';
export * from './vehicleType.service';
import { VehicleTypeService } from './vehicleType.service';
export * from './wallet.service';
import { WalletService } from './wallet.service';
export * from './weather.service';
import { WeatherService } from './weather.service';
export * from './word.service';
import { WordService } from './word.service';
export * from './workflow.service';
import { WorkflowService } from './workflow.service';
export const APIS = [AMQPService, AccountService, AchievementService, ActivityService, AlbumService, AnalyticsService, AppDataService, ApplicationService, ApplicationConfigService, AssetService, AssignmentService, AudienceService, BidService, BillableEntityService, BillingInfoService, CSVImportService, CargoTypeService, CarrierService, CategoryService, ConnectionService, ContestService, CreativeService, DependentService, DisbursementService, EmployeeService, EventService, FacebookService, FavoriteService, FilterService, FlagService, GameService, GameLevelService, InviteService, LeaderboardService, LikeService, ListingService, LocationService, LocationApiV2Service, MediaService, MissionService, MissionInviteService, NoteService, NotificationService, ObjectStoreService, OfferService, OfferStatusService, OpenAIService, OptimizeService, OrsonService, PackService, ParticipantsService, PathingService, PostalCodeService, PreviewPersonaService, ProgramService, PurchaseItemService, PurchaseOrderService, QuestionService, RankingService, RatingService, RegionService, ReportingService, ReservationService, RetailerService, RetailerLocationService, RetailerV2Service, RouteService, RouteSettingService, RoutingService, ScheduledNotificationService, ScoreService, SecureAppService, ServiceHubService, ShipmentService, ShipmentBatchService, SimulationService, StopService, StripeService, SubscriptionService, TaskService, TerritoryService, ThemeDescriptorService, ThirdPartyCredentialsService, TicketService, TournamentService, TrackingService, TriggerService, TripService, TwilioService, TwitterService, UserPermissionsService, VatomService, VehicleService, VehicleTypeService, WalletService, WeatherService, WordService, WorkflowService];
