/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class NoteFullResponse (
  valid: Option[Boolean] = None,
  message: Option[String] = None,
  version: Option[Double] = None,
  serializeNulls: Option[Boolean] = None,
  startTimeLog: Option[Long] = None,
  errorCode: Option[String] = None,
  request: Option[Seq[NameStringValueResponse]] = None,
  noteId: Option[Long] = None,
  comment: Option[String] = None,
  tags: Option[String] = None,
  likesCount: Option[Long] = None,
  dislikesCount: Option[Long] = None,
  dateCreated: Option[Long] = None,
  createdDate: Option[Long] = None,
  updatedDate: Option[Long] = None,
  owner: Option[AccountShortResponse] = None,
  latitude: Option[Double] = None,
  longitude: Option[Double] = None,
  locationDescription: Option[String] = None,
  attachedAssets: Option[Seq[AssetShortResponse]] = None,
  likes: Option[Seq[LikeResponse]] = None,
  hasLiked: Option[Boolean] = None,
  hasDisliked: Option[Boolean] = None,
  returning: Option[String] = None
) extends ApiModel

