/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class PreferredLocationResponse (
  ownerId: Option[Long] = None,
  onDate: Option[String] = None,
  onDateMilli: Option[Long] = None,
  hour: Option[Int] = None,
  latitude: Option[Double] = None,
  longitude: Option[Double] = None,
  distance: Option[Double] = None,
  duration: Option[Long] = None,
  startStepId: Option[Long] = None,
  endStepId: Option[Long] = None
) extends ApiModel

