/*
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import org.openapitools.client.model.JsonArray;
import org.openapitools.client.model.JsonObject;
import org.openapitools.client.model.JsonPrimitive;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JsonNull {
  
  @SerializedName("asInt")
  private Integer asInt = null;
  @SerializedName("asJsonObject")
  private JsonObject asJsonObject = null;
  @SerializedName("jsonNull")
  private Boolean jsonNull = null;
  @SerializedName("asString")
  private String asString = null;
  @SerializedName("asBoolean")
  private Boolean asBoolean = null;
  @SerializedName("jsonArray")
  private Boolean jsonArray = null;
  @SerializedName("jsonObject")
  private Boolean jsonObject = null;
  @SerializedName("jsonPrimitive")
  private Boolean jsonPrimitive = null;
  @SerializedName("asJsonArray")
  private JsonArray asJsonArray = null;
  @SerializedName("asJsonPrimitive")
  private JsonPrimitive asJsonPrimitive = null;
  @SerializedName("asJsonNull")
  private JsonNull asJsonNull = null;
  @SerializedName("asNumber")
  private Object asNumber = null;
  @SerializedName("asDouble")
  private Double asDouble = null;
  @SerializedName("asFloat")
  private Float asFloat = null;
  @SerializedName("asLong")
  private Long asLong = null;
  @SerializedName("asByte")
  private byte[] asByte = null;
  @SerializedName("asCharacter")
  private String asCharacter = null;
  @SerializedName("asBigDecimal")
  private BigDecimal asBigDecimal = null;
  @SerializedName("asBigInteger")
  private Integer asBigInteger = null;
  @SerializedName("asShort")
  private Integer asShort = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAsInt() {
    return asInt;
  }
  public void setAsInt(Integer asInt) {
    this.asInt = asInt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JsonObject getAsJsonObject() {
    return asJsonObject;
  }
  public void setAsJsonObject(JsonObject asJsonObject) {
    this.asJsonObject = asJsonObject;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getJsonNull() {
    return jsonNull;
  }
  public void setJsonNull(Boolean jsonNull) {
    this.jsonNull = jsonNull;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAsString() {
    return asString;
  }
  public void setAsString(String asString) {
    this.asString = asString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAsBoolean() {
    return asBoolean;
  }
  public void setAsBoolean(Boolean asBoolean) {
    this.asBoolean = asBoolean;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getJsonArray() {
    return jsonArray;
  }
  public void setJsonArray(Boolean jsonArray) {
    this.jsonArray = jsonArray;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getJsonObject() {
    return jsonObject;
  }
  public void setJsonObject(Boolean jsonObject) {
    this.jsonObject = jsonObject;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getJsonPrimitive() {
    return jsonPrimitive;
  }
  public void setJsonPrimitive(Boolean jsonPrimitive) {
    this.jsonPrimitive = jsonPrimitive;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JsonArray getAsJsonArray() {
    return asJsonArray;
  }
  public void setAsJsonArray(JsonArray asJsonArray) {
    this.asJsonArray = asJsonArray;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JsonPrimitive getAsJsonPrimitive() {
    return asJsonPrimitive;
  }
  public void setAsJsonPrimitive(JsonPrimitive asJsonPrimitive) {
    this.asJsonPrimitive = asJsonPrimitive;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JsonNull getAsJsonNull() {
    return asJsonNull;
  }
  public void setAsJsonNull(JsonNull asJsonNull) {
    this.asJsonNull = asJsonNull;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAsNumber() {
    return asNumber;
  }
  public void setAsNumber(Object asNumber) {
    this.asNumber = asNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getAsDouble() {
    return asDouble;
  }
  public void setAsDouble(Double asDouble) {
    this.asDouble = asDouble;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getAsFloat() {
    return asFloat;
  }
  public void setAsFloat(Float asFloat) {
    this.asFloat = asFloat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getAsLong() {
    return asLong;
  }
  public void setAsLong(Long asLong) {
    this.asLong = asLong;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public byte[] getAsByte() {
    return asByte;
  }
  public void setAsByte(byte[] asByte) {
    this.asByte = asByte;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAsCharacter() {
    return asCharacter;
  }
  public void setAsCharacter(String asCharacter) {
    this.asCharacter = asCharacter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getAsBigDecimal() {
    return asBigDecimal;
  }
  public void setAsBigDecimal(BigDecimal asBigDecimal) {
    this.asBigDecimal = asBigDecimal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAsBigInteger() {
    return asBigInteger;
  }
  public void setAsBigInteger(Integer asBigInteger) {
    this.asBigInteger = asBigInteger;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAsShort() {
    return asShort;
  }
  public void setAsShort(Integer asShort) {
    this.asShort = asShort;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonNull jsonNull = (JsonNull) o;
    return (this.asInt == null ? jsonNull.asInt == null : this.asInt.equals(jsonNull.asInt)) &&
        (this.asJsonObject == null ? jsonNull.asJsonObject == null : this.asJsonObject.equals(jsonNull.asJsonObject)) &&
        (this.jsonNull == null ? jsonNull.jsonNull == null : this.jsonNull.equals(jsonNull.jsonNull)) &&
        (this.asString == null ? jsonNull.asString == null : this.asString.equals(jsonNull.asString)) &&
        (this.asBoolean == null ? jsonNull.asBoolean == null : this.asBoolean.equals(jsonNull.asBoolean)) &&
        (this.jsonArray == null ? jsonNull.jsonArray == null : this.jsonArray.equals(jsonNull.jsonArray)) &&
        (this.jsonObject == null ? jsonNull.jsonObject == null : this.jsonObject.equals(jsonNull.jsonObject)) &&
        (this.jsonPrimitive == null ? jsonNull.jsonPrimitive == null : this.jsonPrimitive.equals(jsonNull.jsonPrimitive)) &&
        (this.asJsonArray == null ? jsonNull.asJsonArray == null : this.asJsonArray.equals(jsonNull.asJsonArray)) &&
        (this.asJsonPrimitive == null ? jsonNull.asJsonPrimitive == null : this.asJsonPrimitive.equals(jsonNull.asJsonPrimitive)) &&
        (this.asJsonNull == null ? jsonNull.asJsonNull == null : this.asJsonNull.equals(jsonNull.asJsonNull)) &&
        (this.asNumber == null ? jsonNull.asNumber == null : this.asNumber.equals(jsonNull.asNumber)) &&
        (this.asDouble == null ? jsonNull.asDouble == null : this.asDouble.equals(jsonNull.asDouble)) &&
        (this.asFloat == null ? jsonNull.asFloat == null : this.asFloat.equals(jsonNull.asFloat)) &&
        (this.asLong == null ? jsonNull.asLong == null : this.asLong.equals(jsonNull.asLong)) &&
        (this.asByte == null ? jsonNull.asByte == null : this.asByte.equals(jsonNull.asByte)) &&
        (this.asCharacter == null ? jsonNull.asCharacter == null : this.asCharacter.equals(jsonNull.asCharacter)) &&
        (this.asBigDecimal == null ? jsonNull.asBigDecimal == null : this.asBigDecimal.equals(jsonNull.asBigDecimal)) &&
        (this.asBigInteger == null ? jsonNull.asBigInteger == null : this.asBigInteger.equals(jsonNull.asBigInteger)) &&
        (this.asShort == null ? jsonNull.asShort == null : this.asShort.equals(jsonNull.asShort));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.asInt == null ? 0: this.asInt.hashCode());
    result = 31 * result + (this.asJsonObject == null ? 0: this.asJsonObject.hashCode());
    result = 31 * result + (this.jsonNull == null ? 0: this.jsonNull.hashCode());
    result = 31 * result + (this.asString == null ? 0: this.asString.hashCode());
    result = 31 * result + (this.asBoolean == null ? 0: this.asBoolean.hashCode());
    result = 31 * result + (this.jsonArray == null ? 0: this.jsonArray.hashCode());
    result = 31 * result + (this.jsonObject == null ? 0: this.jsonObject.hashCode());
    result = 31 * result + (this.jsonPrimitive == null ? 0: this.jsonPrimitive.hashCode());
    result = 31 * result + (this.asJsonArray == null ? 0: this.asJsonArray.hashCode());
    result = 31 * result + (this.asJsonPrimitive == null ? 0: this.asJsonPrimitive.hashCode());
    result = 31 * result + (this.asJsonNull == null ? 0: this.asJsonNull.hashCode());
    result = 31 * result + (this.asNumber == null ? 0: this.asNumber.hashCode());
    result = 31 * result + (this.asDouble == null ? 0: this.asDouble.hashCode());
    result = 31 * result + (this.asFloat == null ? 0: this.asFloat.hashCode());
    result = 31 * result + (this.asLong == null ? 0: this.asLong.hashCode());
    result = 31 * result + (this.asByte == null ? 0: this.asByte.hashCode());
    result = 31 * result + (this.asCharacter == null ? 0: this.asCharacter.hashCode());
    result = 31 * result + (this.asBigDecimal == null ? 0: this.asBigDecimal.hashCode());
    result = 31 * result + (this.asBigInteger == null ? 0: this.asBigInteger.hashCode());
    result = 31 * result + (this.asShort == null ? 0: this.asShort.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonNull {\n");
    
    sb.append("  asInt: ").append(asInt).append("\n");
    sb.append("  asJsonObject: ").append(asJsonObject).append("\n");
    sb.append("  jsonNull: ").append(jsonNull).append("\n");
    sb.append("  asString: ").append(asString).append("\n");
    sb.append("  asBoolean: ").append(asBoolean).append("\n");
    sb.append("  jsonArray: ").append(jsonArray).append("\n");
    sb.append("  jsonObject: ").append(jsonObject).append("\n");
    sb.append("  jsonPrimitive: ").append(jsonPrimitive).append("\n");
    sb.append("  asJsonArray: ").append(asJsonArray).append("\n");
    sb.append("  asJsonPrimitive: ").append(asJsonPrimitive).append("\n");
    sb.append("  asJsonNull: ").append(asJsonNull).append("\n");
    sb.append("  asNumber: ").append(asNumber).append("\n");
    sb.append("  asDouble: ").append(asDouble).append("\n");
    sb.append("  asFloat: ").append(asFloat).append("\n");
    sb.append("  asLong: ").append(asLong).append("\n");
    sb.append("  asByte: ").append(asByte).append("\n");
    sb.append("  asCharacter: ").append(asCharacter).append("\n");
    sb.append("  asBigDecimal: ").append(asBigDecimal).append("\n");
    sb.append("  asBigInteger: ").append(asBigInteger).append("\n");
    sb.append("  asShort: ").append(asShort).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
