/*
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import org.openapitools.client.model.Verb;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TwiMLResponse {
  
  @SerializedName("tag")
  private String tag = null;
  @SerializedName("body")
  private String body = null;
  @SerializedName("attributes")
  private Map<String, String> attributes = null;
  @SerializedName("children")
  private List<Verb> children = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }
  public void setTag(String tag) {
    this.tag = tag;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBody() {
    return body;
  }
  public void setBody(String body) {
    this.body = body;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }
  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Verb> getChildren() {
    return children;
  }
  public void setChildren(List<Verb> children) {
    this.children = children;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TwiMLResponse twiMLResponse = (TwiMLResponse) o;
    return (this.tag == null ? twiMLResponse.tag == null : this.tag.equals(twiMLResponse.tag)) &&
        (this.body == null ? twiMLResponse.body == null : this.body.equals(twiMLResponse.body)) &&
        (this.attributes == null ? twiMLResponse.attributes == null : this.attributes.equals(twiMLResponse.attributes)) &&
        (this.children == null ? twiMLResponse.children == null : this.children.equals(twiMLResponse.children));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tag == null ? 0: this.tag.hashCode());
    result = 31 * result + (this.body == null ? 0: this.body.hashCode());
    result = 31 * result + (this.attributes == null ? 0: this.attributes.hashCode());
    result = 31 * result + (this.children == null ? 0: this.children.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TwiMLResponse {\n");
    
    sb.append("  tag: ").append(tag).append("\n");
    sb.append("  body: ").append(body).append("\n");
    sb.append("  attributes: ").append(attributes).append("\n");
    sb.append("  children: ").append(children).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
