#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/list_count_response.h"
#include "../model/offer_list_response.h"
#include "../model/offer_response.h"
#include "../model/offer_short_response.h"
#include "../model/offer_transaction_response.h"
#include "../model/retailer_offer_response.h"
#include "../model/sirqul_response.h"

// Enum BARCODETYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_BARCODETYPE_NULL = 0, sirqul_iot_platform_createOffer_BARCODETYPE_NONE, sirqul_iot_platform_createOffer_BARCODETYPE_UPC, sirqul_iot_platform_createOffer_BARCODETYPE_CODE_128, sirqul_iot_platform_createOffer_BARCODETYPE_QR, sirqul_iot_platform_createOffer_BARCODETYPE_CUSTOM_MEDIA } sirqul_iot_platform_createOffer_barcodeType_e;

// Enum OFFERTYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_OFFERTYPE_NULL = 0, sirqul_iot_platform_createOffer_OFFERTYPE_VOUCHER, sirqul_iot_platform_createOffer_OFFERTYPE_COUPON, sirqul_iot_platform_createOffer_OFFERTYPE_PRODUCT, sirqul_iot_platform_createOffer_OFFERTYPE_MEDIA, sirqul_iot_platform_createOffer_OFFERTYPE_EVENT, sirqul_iot_platform_createOffer_OFFERTYPE_DEVICE } sirqul_iot_platform_createOffer_offerType_e;

// Enum SPECIALOFFERTYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_NULL = 0, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_ALL, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_RESERVABLE, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_REGULAR_OFFER, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_ACT_NOW, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_GET_THERE_NOW, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_SQOOT, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_TICKETS, sirqul_iot_platform_createOffer_SPECIALOFFERTYPE_YIPIT } sirqul_iot_platform_createOffer_specialOfferType_e;

// Enum OFFERVISIBILITY for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_OFFERVISIBILITY_NULL = 0, sirqul_iot_platform_createOffer_OFFERVISIBILITY__PUBLIC, sirqul_iot_platform_createOffer_OFFERVISIBILITY_LISTABLE, sirqul_iot_platform_createOffer_OFFERVISIBILITY_REWARDABLE, sirqul_iot_platform_createOffer_OFFERVISIBILITY_TRIGGERABLE, sirqul_iot_platform_createOffer_OFFERVISIBILITY__PRIVATE } sirqul_iot_platform_createOffer_offerVisibility_e;

// Enum PRODUCTTYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_PRODUCTTYPE_NULL = 0, sirqul_iot_platform_createOffer_PRODUCTTYPE_APPAREL, sirqul_iot_platform_createOffer_PRODUCTTYPE_APPLIANCES, sirqul_iot_platform_createOffer_PRODUCTTYPE_APPS, sirqul_iot_platform_createOffer_PRODUCTTYPE_ARTS_CRAFTS, sirqul_iot_platform_createOffer_PRODUCTTYPE_AUTOMOTIVE, sirqul_iot_platform_createOffer_PRODUCTTYPE_BABY, sirqul_iot_platform_createOffer_PRODUCTTYPE_BEAUTY, sirqul_iot_platform_createOffer_PRODUCTTYPE_BOOKS, sirqul_iot_platform_createOffer_PRODUCTTYPE_CLASSICAL, sirqul_iot_platform_createOffer_PRODUCTTYPE_COLLECTIBLES, sirqul_iot_platform_createOffer_PRODUCTTYPE_DVD, sirqul_iot_platform_createOffer_PRODUCTTYPE_ELECTRONICS, sirqul_iot_platform_createOffer_PRODUCTTYPE_GIFT_CARDS, sirqul_iot_platform_createOffer_PRODUCTTYPE_GOURMET_FOOD, sirqul_iot_platform_createOffer_PRODUCTTYPE_GROCERY, sirqul_iot_platform_createOffer_PRODUCTTYPE_HEALTH_PERSONAL_CARE, sirqul_iot_platform_createOffer_PRODUCTTYPE_HOME_GARDEN, sirqul_iot_platform_createOffer_PRODUCTTYPE_INDUSTRIAL, sirqul_iot_platform_createOffer_PRODUCTTYPE_JEWELRY, sirqul_iot_platform_createOffer_PRODUCTTYPE_KITCHEN, sirqul_iot_platform_createOffer_PRODUCTTYPE_LAWN_GARDEN, sirqul_iot_platform_createOffer_PRODUCTTYPE_MAGAZINES, sirqul_iot_platform_createOffer_PRODUCTTYPE_MISCELLANEOUS, sirqul_iot_platform_createOffer_PRODUCTTYPE_MUSICAL_INSTRUMENTS, sirqul_iot_platform_createOffer_PRODUCTTYPE_OFFICE_PRODUCTS, sirqul_iot_platform_createOffer_PRODUCTTYPE_OTHER, sirqul_iot_platform_createOffer_PRODUCTTYPE_OUTDOOR_LIVING, sirqul_iot_platform_createOffer_PRODUCTTYPE_PC_HARDWARE, sirqul_iot_platform_createOffer_PRODUCTTYPE_PET_SUPPLIES, sirqul_iot_platform_createOffer_PRODUCTTYPE_SHOES, sirqul_iot_platform_createOffer_PRODUCTTYPE_SOFTWARE, sirqul_iot_platform_createOffer_PRODUCTTYPE_SPORTING_GOODS, sirqul_iot_platform_createOffer_PRODUCTTYPE_TOOLS, sirqul_iot_platform_createOffer_PRODUCTTYPE_TOYS, sirqul_iot_platform_createOffer_PRODUCTTYPE_VIDEO_GAMES, sirqul_iot_platform_createOffer_PRODUCTTYPE_WATCHES, sirqul_iot_platform_createOffer_PRODUCTTYPE_WIRELESS, sirqul_iot_platform_createOffer_PRODUCTTYPE_WIRELESS_ACCESSORIES } sirqul_iot_platform_createOffer_productType_e;

// Enum CONDITIONTYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_CONDITIONTYPE_NULL = 0, sirqul_iot_platform_createOffer_CONDITIONTYPE__NEW, sirqul_iot_platform_createOffer_CONDITIONTYPE_USED, sirqul_iot_platform_createOffer_CONDITIONTYPE_REFURBISHED, sirqul_iot_platform_createOffer_CONDITIONTYPE_OTHER } sirqul_iot_platform_createOffer_conditionType_e;

// Enum UNIT for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_UNIT_NULL = 0, sirqul_iot_platform_createOffer_UNIT_MILIMETER, sirqul_iot_platform_createOffer_UNIT_CENTIMETER, sirqul_iot_platform_createOffer_UNIT_METER, sirqul_iot_platform_createOffer_UNIT_INCH, sirqul_iot_platform_createOffer_UNIT_FOOT, sirqul_iot_platform_createOffer_UNIT_YARD } sirqul_iot_platform_createOffer_unit_e;

// Enum MEDIATYPE for OfferAPI_createOffer
typedef enum  { sirqul_iot_platform_createOffer_MEDIATYPE_NULL = 0, sirqul_iot_platform_createOffer_MEDIATYPE_APK, sirqul_iot_platform_createOffer_MEDIATYPE_APPLICATION, sirqul_iot_platform_createOffer_MEDIATYPE_IMAGE, sirqul_iot_platform_createOffer_MEDIATYPE_AUDIO, sirqul_iot_platform_createOffer_MEDIATYPE_VIDEO, sirqul_iot_platform_createOffer_MEDIATYPE_MULTIPART, sirqul_iot_platform_createOffer_MEDIATYPE_BAR_CODE, sirqul_iot_platform_createOffer_MEDIATYPE_TEXT, sirqul_iot_platform_createOffer_MEDIATYPE_OTHER } sirqul_iot_platform_createOffer_mediaType_e;

// Enum DISTANCEUNIT for OfferAPI_getOfferListCounts
typedef enum  { sirqul_iot_platform_getOfferListCounts_DISTANCEUNIT_NULL = 0, sirqul_iot_platform_getOfferListCounts_DISTANCEUNIT_MILES, sirqul_iot_platform_getOfferListCounts_DISTANCEUNIT_KILOMETERS } sirqul_iot_platform_getOfferListCounts_distanceUnit_e;

// Enum SORTFIELD for OfferAPI_getOfferLocationsForRetailers
typedef enum  { sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_NULL = 0, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_ID, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_CREATED, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_UPDATED, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_DELETED, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_SEARCH_TAGS, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_ACTIVE, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_OFFER_ID, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_ACTIVATED, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_EXPIRES, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_TITLE, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_SUBTITLE, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_DETAILS, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_OFFER_TYPE, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_SPECIAL_OFFER_TYPE, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_OFFER_VISIBILITY, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_RETAILER_ID, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_RETAILER_LOCATION_ID, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_BILLABLE_ENTITY_ID, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_BILLABLE_ENTITY_NAME, sirqul_iot_platform_getOfferLocationsForRetailers_SORTFIELD_RESPONSIBLE_DISPLAY } sirqul_iot_platform_getOfferLocationsForRetailers_sortField_e;

// Enum OFFERTYPE for OfferAPI_getOfferLocationsForRetailers
typedef enum  { sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_NULL = 0, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_VOUCHER, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_COUPON, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_PRODUCT, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_MEDIA, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_EVENT, sirqul_iot_platform_getOfferLocationsForRetailers_OFFERTYPE_DEVICE } sirqul_iot_platform_getOfferLocationsForRetailers_offerType_e;

// Enum SPECIALOFFERTYPE for OfferAPI_getOfferLocationsForRetailers
typedef enum  { sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_NULL = 0, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_ALL, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_RESERVABLE, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_REGULAR_OFFER, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_ACT_NOW, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_GET_THERE_NOW, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_SQOOT, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_TICKETS, sirqul_iot_platform_getOfferLocationsForRetailers_SPECIALOFFERTYPE_YIPIT } sirqul_iot_platform_getOfferLocationsForRetailers_specialOfferType_e;

// Enum DEVICESTATUS for OfferAPI_getOfferLocationsForRetailers
typedef enum  { sirqul_iot_platform_getOfferLocationsForRetailers_DEVICESTATUS_NULL = 0, sirqul_iot_platform_getOfferLocationsForRetailers_DEVICESTATUS_RUNNING, sirqul_iot_platform_getOfferLocationsForRetailers_DEVICESTATUS_WARNING, sirqul_iot_platform_getOfferLocationsForRetailers_DEVICESTATUS_DOWN } sirqul_iot_platform_getOfferLocationsForRetailers_deviceStatus_e;

// Enum OFFERVISIBILITY for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY_NULL = 0, sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY__PUBLIC, sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY_LISTABLE, sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY_REWARDABLE, sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY_TRIGGERABLE, sirqul_iot_platform_getOffersForRetailers_OFFERVISIBILITY__PRIVATE } sirqul_iot_platform_getOffersForRetailers_offerVisibility_e;

// Enum SORTFIELD for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_SORTFIELD_NULL = 0, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_ID, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_CREATED, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_UPDATED, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_DELETED, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_SEARCH_TAGS, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_ACTIVE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_ACTIVATED, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_EXPIRES, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_REDEEMABLE_START, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_REDEEMABLE_END, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_TITLE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_SUBTITLE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_DETAILS, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_OFFER_TYPE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_SPECIAL_OFFER_TYPE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_OFFER_VISIBILITY, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_ESTIMATED_VALUE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_VOUCHER_PRICE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_VOUCHER_DISCOUNT_PRICE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_FULL_PRICE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_DICOUNT_PRICE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_TICKETS_REWARD, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_AVAILABILITY_DATE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RELEASE_DATE, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RETAILER_ID, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RETAILER_NAME, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RETAILER_LOCATION_ID, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RETAILER_LOCATION_NAME, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_BILLABLE_ENTITY_ID, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_BILLABLE_ENTITY_NAME, sirqul_iot_platform_getOffersForRetailers_SORTFIELD_RESPONSIBLE_DISPLAY } sirqul_iot_platform_getOffersForRetailers_sortField_e;

// Enum COUPONTYPE for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_NULL = 0, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_VOUCHER, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_COUPON, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_PRODUCT, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_MEDIA, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_EVENT, sirqul_iot_platform_getOffersForRetailers_COUPONTYPE_DEVICE } sirqul_iot_platform_getOffersForRetailers_couponType_e;

// Enum OFFERTYPE for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_NULL = 0, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_VOUCHER, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_COUPON, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_PRODUCT, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_MEDIA, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_EVENT, sirqul_iot_platform_getOffersForRetailers_OFFERTYPE_DEVICE } sirqul_iot_platform_getOffersForRetailers_offerType_e;

// Enum SPECIALOFFERTYPE for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_NULL = 0, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_ALL, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_RESERVABLE, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_REGULAR_OFFER, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_ACT_NOW, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_GET_THERE_NOW, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_SQOOT, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_TICKETS, sirqul_iot_platform_getOffersForRetailers_SPECIALOFFERTYPE_YIPIT } sirqul_iot_platform_getOffersForRetailers_specialOfferType_e;

// Enum DEVICESTATUS for OfferAPI_getOffersForRetailers
typedef enum  { sirqul_iot_platform_getOffersForRetailers_DEVICESTATUS_NULL = 0, sirqul_iot_platform_getOffersForRetailers_DEVICESTATUS_RUNNING, sirqul_iot_platform_getOffersForRetailers_DEVICESTATUS_WARNING, sirqul_iot_platform_getOffersForRetailers_DEVICESTATUS_DOWN } sirqul_iot_platform_getOffersForRetailers_deviceStatus_e;

// Enum SORTFIELD for OfferAPI_searchOfferTransactionsForRetailers
typedef enum  { sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_NULL = 0, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_ID, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_CREATED, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_UPDATED, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_DELETED, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_SEARCH_TAGS, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_ACTIVE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_ACTIVATED, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_EXPIRES, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_TITLE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_SUBTITLE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_DETAILS, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_OFFER_TYPE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_SPECIAL_OFFER_TYPE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_OFFER_VISIBILITY, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_REDEEMABLE_START, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_REDEEMABLE_END, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_CUSTOMER_ID, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_CUSTOMER_DISPLAY, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_RETAILER_ID, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_RETAILER_NAME, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_RETAILER_LOCATION_ID, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_RETAILER_LOCATION_NAME, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_BILLABLE_ENTITY_ID, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_BILLABLE_ENTITY_NAME, sirqul_iot_platform_searchOfferTransactionsForRetailers_SORTFIELD_RESPONSIBLE_DISPLAY } sirqul_iot_platform_searchOfferTransactionsForRetailers_sortField_e;

// Enum COUPONTYPE for OfferAPI_searchOfferTransactionsForRetailers
typedef enum  { sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_NULL = 0, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_VOUCHER, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_COUPON, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_PRODUCT, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_MEDIA, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_EVENT, sirqul_iot_platform_searchOfferTransactionsForRetailers_COUPONTYPE_DEVICE } sirqul_iot_platform_searchOfferTransactionsForRetailers_couponType_e;

// Enum OFFERTYPE for OfferAPI_searchOfferTransactionsForRetailers
typedef enum  { sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_NULL = 0, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_VOUCHER, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_COUPON, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_PRODUCT, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_MEDIA, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_EVENT, sirqul_iot_platform_searchOfferTransactionsForRetailers_OFFERTYPE_DEVICE } sirqul_iot_platform_searchOfferTransactionsForRetailers_offerType_e;

// Enum SPECIALOFFERTYPE for OfferAPI_searchOfferTransactionsForRetailers
typedef enum  { sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_NULL = 0, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_ALL, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_RESERVABLE, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_REGULAR_OFFER, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_ACT_NOW, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_GET_THERE_NOW, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_SQOOT, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_TICKETS, sirqul_iot_platform_searchOfferTransactionsForRetailers_SPECIALOFFERTYPE_YIPIT } sirqul_iot_platform_searchOfferTransactionsForRetailers_specialOfferType_e;

// Enum RECOMMENDATIONTYPE for OfferAPI_searchOffersForConsumer
typedef enum  { sirqul_iot_platform_searchOffersForConsumer_RECOMMENDATIONTYPE_NULL = 0, sirqul_iot_platform_searchOffersForConsumer_RECOMMENDATIONTYPE_WALLET, sirqul_iot_platform_searchOffersForConsumer_RECOMMENDATIONTYPE_CLICKS, sirqul_iot_platform_searchOffersForConsumer_RECOMMENDATIONTYPE_BLENDED } sirqul_iot_platform_searchOffersForConsumer_recommendationType_e;

// Enum DISTANCEUNIT for OfferAPI_searchOffersForConsumer
typedef enum  { sirqul_iot_platform_searchOffersForConsumer_DISTANCEUNIT_NULL = 0, sirqul_iot_platform_searchOffersForConsumer_DISTANCEUNIT_MILES, sirqul_iot_platform_searchOffersForConsumer_DISTANCEUNIT_KILOMETERS } sirqul_iot_platform_searchOffersForConsumer_distanceUnit_e;

// Enum GROUPBY for OfferAPI_searchOffersForConsumer
typedef enum  { sirqul_iot_platform_searchOffersForConsumer_GROUPBY_NULL = 0, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_ID, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_CREATED, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_UPDATED, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_DELETED, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_SEARCH_TAGS, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_ACTIVE, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_OFFER_ID, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_ACTIVATED, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_EXPIRES, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_TITLE, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_SUBTITLE, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_DETAILS, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_OFFER_TYPE, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_SPECIAL_OFFER_TYPE, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_OFFER_VISIBILITY, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_RETAILER_ID, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_RETAILER_LOCATION_ID, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_BILLABLE_ENTITY_ID, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_BILLABLE_ENTITY_NAME, sirqul_iot_platform_searchOffersForConsumer_GROUPBY_RESPONSIBLE_DISPLAY } sirqul_iot_platform_searchOffersForConsumer_groupBy_e;

// Enum BARCODETYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_BARCODETYPE_NULL = 0, sirqul_iot_platform_updateOffer_BARCODETYPE_NONE, sirqul_iot_platform_updateOffer_BARCODETYPE_UPC, sirqul_iot_platform_updateOffer_BARCODETYPE_CODE_128, sirqul_iot_platform_updateOffer_BARCODETYPE_QR, sirqul_iot_platform_updateOffer_BARCODETYPE_CUSTOM_MEDIA } sirqul_iot_platform_updateOffer_barcodeType_e;

// Enum OFFERTYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_OFFERTYPE_NULL = 0, sirqul_iot_platform_updateOffer_OFFERTYPE_VOUCHER, sirqul_iot_platform_updateOffer_OFFERTYPE_COUPON, sirqul_iot_platform_updateOffer_OFFERTYPE_PRODUCT, sirqul_iot_platform_updateOffer_OFFERTYPE_MEDIA, sirqul_iot_platform_updateOffer_OFFERTYPE_EVENT, sirqul_iot_platform_updateOffer_OFFERTYPE_DEVICE } sirqul_iot_platform_updateOffer_offerType_e;

// Enum SPECIALOFFERTYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_NULL = 0, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_ALL, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_RESERVABLE, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_REGULAR_OFFER, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_ACT_NOW, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_GET_THERE_NOW, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_SQOOT, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_TICKETS, sirqul_iot_platform_updateOffer_SPECIALOFFERTYPE_YIPIT } sirqul_iot_platform_updateOffer_specialOfferType_e;

// Enum OFFERVISIBILITY for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_OFFERVISIBILITY_NULL = 0, sirqul_iot_platform_updateOffer_OFFERVISIBILITY__PUBLIC, sirqul_iot_platform_updateOffer_OFFERVISIBILITY_LISTABLE, sirqul_iot_platform_updateOffer_OFFERVISIBILITY_REWARDABLE, sirqul_iot_platform_updateOffer_OFFERVISIBILITY_TRIGGERABLE, sirqul_iot_platform_updateOffer_OFFERVISIBILITY__PRIVATE } sirqul_iot_platform_updateOffer_offerVisibility_e;

// Enum PRODUCTTYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_PRODUCTTYPE_NULL = 0, sirqul_iot_platform_updateOffer_PRODUCTTYPE_APPAREL, sirqul_iot_platform_updateOffer_PRODUCTTYPE_APPLIANCES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_APPS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_ARTS_CRAFTS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_AUTOMOTIVE, sirqul_iot_platform_updateOffer_PRODUCTTYPE_BABY, sirqul_iot_platform_updateOffer_PRODUCTTYPE_BEAUTY, sirqul_iot_platform_updateOffer_PRODUCTTYPE_BOOKS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_CLASSICAL, sirqul_iot_platform_updateOffer_PRODUCTTYPE_COLLECTIBLES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_DVD, sirqul_iot_platform_updateOffer_PRODUCTTYPE_ELECTRONICS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_GIFT_CARDS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_GOURMET_FOOD, sirqul_iot_platform_updateOffer_PRODUCTTYPE_GROCERY, sirqul_iot_platform_updateOffer_PRODUCTTYPE_HEALTH_PERSONAL_CARE, sirqul_iot_platform_updateOffer_PRODUCTTYPE_HOME_GARDEN, sirqul_iot_platform_updateOffer_PRODUCTTYPE_INDUSTRIAL, sirqul_iot_platform_updateOffer_PRODUCTTYPE_JEWELRY, sirqul_iot_platform_updateOffer_PRODUCTTYPE_KITCHEN, sirqul_iot_platform_updateOffer_PRODUCTTYPE_LAWN_GARDEN, sirqul_iot_platform_updateOffer_PRODUCTTYPE_MAGAZINES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_MISCELLANEOUS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_MUSICAL_INSTRUMENTS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_OFFICE_PRODUCTS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_OTHER, sirqul_iot_platform_updateOffer_PRODUCTTYPE_OUTDOOR_LIVING, sirqul_iot_platform_updateOffer_PRODUCTTYPE_PC_HARDWARE, sirqul_iot_platform_updateOffer_PRODUCTTYPE_PET_SUPPLIES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_SHOES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_SOFTWARE, sirqul_iot_platform_updateOffer_PRODUCTTYPE_SPORTING_GOODS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_TOOLS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_TOYS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_VIDEO_GAMES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_WATCHES, sirqul_iot_platform_updateOffer_PRODUCTTYPE_WIRELESS, sirqul_iot_platform_updateOffer_PRODUCTTYPE_WIRELESS_ACCESSORIES } sirqul_iot_platform_updateOffer_productType_e;

// Enum CONDITIONTYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_CONDITIONTYPE_NULL = 0, sirqul_iot_platform_updateOffer_CONDITIONTYPE__NEW, sirqul_iot_platform_updateOffer_CONDITIONTYPE_USED, sirqul_iot_platform_updateOffer_CONDITIONTYPE_REFURBISHED, sirqul_iot_platform_updateOffer_CONDITIONTYPE_OTHER } sirqul_iot_platform_updateOffer_conditionType_e;

// Enum UNIT for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_UNIT_NULL = 0, sirqul_iot_platform_updateOffer_UNIT_MILIMETER, sirqul_iot_platform_updateOffer_UNIT_CENTIMETER, sirqul_iot_platform_updateOffer_UNIT_METER, sirqul_iot_platform_updateOffer_UNIT_INCH, sirqul_iot_platform_updateOffer_UNIT_FOOT, sirqul_iot_platform_updateOffer_UNIT_YARD } sirqul_iot_platform_updateOffer_unit_e;

// Enum MEDIATYPE for OfferAPI_updateOffer
typedef enum  { sirqul_iot_platform_updateOffer_MEDIATYPE_NULL = 0, sirqul_iot_platform_updateOffer_MEDIATYPE_APK, sirqul_iot_platform_updateOffer_MEDIATYPE_APPLICATION, sirqul_iot_platform_updateOffer_MEDIATYPE_IMAGE, sirqul_iot_platform_updateOffer_MEDIATYPE_AUDIO, sirqul_iot_platform_updateOffer_MEDIATYPE_VIDEO, sirqul_iot_platform_updateOffer_MEDIATYPE_MULTIPART, sirqul_iot_platform_updateOffer_MEDIATYPE_BAR_CODE, sirqul_iot_platform_updateOffer_MEDIATYPE_TEXT, sirqul_iot_platform_updateOffer_MEDIATYPE_OTHER } sirqul_iot_platform_updateOffer_mediaType_e;


// Update Offer Locations
//
// Batch update offer locations.
//
sirqul_response_t*
OfferAPI_batchUpdateOfferLocations(apiClient_t *apiClient, double version, char *data, char *deviceId, long accountId);


// Create Offer
//
// Create an offer and assign it to the provided retailer locations.
//
retailer_offer_response_t*
OfferAPI_createOffer(apiClient_t *apiClient, double version, int *includeOfferLocations, char *title, sirqul_iot_platform_createOffer_barcodeType_e barcodeType, int *noExpiration, int *availableLimit, int *availableLimitPerUser, int *addedLimit, int *viewLimit, int *maxPrints, long ticketPrice, double fullPrice, double discountPrice, sirqul_iot_platform_createOffer_offerType_e offerType, sirqul_iot_platform_createOffer_specialOfferType_e specialOfferType, sirqul_iot_platform_createOffer_offerVisibility_e offerVisibility, int *active, char *deviceId, long accountId, char *tags, long parentOfferId, char *retailerLocationIds, char *offerLocations, char *subTitle, char *details, char *subDetails, char *finePrint, char *barcodeEntry, char *externalRedeemOptions, char *externalUrl, char *externalId, char *ticketsRewardType, long ticketsReward, long activated, long expires, char *ticketPriceType, int *showRemaining, int *showRedeemed, int *replaced, int *featured, char *categoryIds, char *filterIds, long barcodeAssetId, long imageAssetId, long imageAssetId1, long imageAssetId2, long imageAssetId3, long imageAssetId4, long imageAssetId5, char *publisher, long redeemableStart, long redeemableEnd, char *brand, sirqul_iot_platform_createOffer_productType_e productType, sirqul_iot_platform_createOffer_conditionType_e conditionType, char *isbn, char *asin, char *catalogNumbers, char *department, char *features, double minimumPrice, double width, double height, double depth, double weight, sirqul_iot_platform_createOffer_unit_e unit, char *studio, char *parentalRating, long publishDate, long availabilityDate, long sizeId, long listingId, sirqul_iot_platform_createOffer_mediaType_e mediaType, int *duration, char *author, long releaseDate, char *collectionIds, int *rebootTimeHour, int *rebootTimeMinute, int *idleTimeoutInSecond, char *serialNumber, char *udid, char *deviceType, double devicePower, double deviceInterference, char *availability, char *availabilitySummary);


// Delete Offer
//
// Set the deleted timestamp to current time. This effectively deletes the offer since all queries should ignore any records with a deleted time stamp.
//
sirqul_response_t*
OfferAPI_deleteOffer(apiClient_t *apiClient, double version, long offerId, char *deviceId, long accountId);


// Delete Offer Location
//
// Set the deleted timestamp to current time. This effectively deletes the offer location since all queries should ignore any records with a deleted time stamp.
//
sirqul_response_t*
OfferAPI_deleteOfferLocation(apiClient_t *apiClient, double version, long offerLocationId, char *deviceId, long accountId);


// Get Offer
//
// Gets the details of an offer that the user has access to.
//
retailer_offer_response_t*
OfferAPI_getOffer(apiClient_t *apiClient, double version, long offerId, int *includeOfferLocations, char *deviceId, long accountId);


// Get Offer
//
// Gets offer or offer location details as a consumer.  Will check if it is a favorite if the deviceId/accountId is provided.  If the offerId is provided it will look up the main offer and ignore the the offerLocationId. If no offerId is provided then an offerLocationId must be specified.
//
offer_response_t*
OfferAPI_getOfferDetails(apiClient_t *apiClient, double version, char *deviceId, long accountId, long offerId, long offerLocationId, double distance, double latitude, double longitude, int *includeOfferLocations, int *includeRetailerLocations, int *includeChildOffers);


// Get Offers (Counts)
//
// Gets the offer list counts.
//
list_count_response_t*
OfferAPI_getOfferListCounts(apiClient_t *apiClient, double version, double latitude, double longitude, double searchRange, sirqul_iot_platform_getOfferListCounts_distanceUnit_e distanceUnit);


// Get Offer Location
//
// Gets the offer location by offer location id or udid (of a device)
//
offer_short_response_t*
OfferAPI_getOfferLocation(apiClient_t *apiClient, double version, long offerLocationId, char *udid);


// Search Offer Locations
//
// Searches on offer locations, which are records that represent an offer that has been assigned to a retailer location. If an offer does not have any locations assigned, then it will NOT be returned.
//
list_t*
OfferAPI_getOfferLocationsForRetailers(apiClient_t *apiClient, double version, sirqul_iot_platform_getOfferLocationsForRetailers_sortField_e sortField, int *descending, int *start, int *limit, int *activeOnly, int *includeRetailerLocation, char *deviceId, long accountId, char *keyword, long retailerId, long retailerLocationId, sirqul_iot_platform_getOfferLocationsForRetailers_offerType_e offerType, sirqul_iot_platform_getOfferLocationsForRetailers_specialOfferType_e specialOfferType, char *barcodeType, char *barcodeEntry, char *isbn, char *asin, sirqul_iot_platform_getOfferLocationsForRetailers_deviceStatus_e deviceStatus, int *needsNotificationSent, long lastNotificationSent);


// Search Offers
//
// Searches on offers that the account has access to.
//
list_t*
OfferAPI_getOffersForRetailers(apiClient_t *apiClient, double version, sirqul_iot_platform_getOffersForRetailers_offerVisibility_e offerVisibility, sirqul_iot_platform_getOffersForRetailers_sortField_e sortField, int *descending, int *start, int *limit, int *availableOnly, int *activeOnly, int *includeCategories, int *includeFilters, int *includeOfferLocations, char *deviceId, long accountId, char *categoryIds, char *filterIds, char *q, char *keyword, long retailerId, long retailerLocationId, sirqul_iot_platform_getOffersForRetailers_couponType_e couponType, sirqul_iot_platform_getOffersForRetailers_offerType_e offerType, char *offerTypes, sirqul_iot_platform_getOffersForRetailers_specialOfferType_e specialOfferType, int *_i, int *_l, char *barcodeType, char *barcodeEntry, char *isbn, char *asin, sirqul_iot_platform_getOffersForRetailers_deviceStatus_e deviceStatus, int *needsNotificationSent, long lastNotificationSent);


// Update Offer Transaction
//
// Redeems an offer.
//
sirqul_response_t*
OfferAPI_redeemOfferTransaction(apiClient_t *apiClient, double version, long offerTransactionId, int *status, char *deviceId, long accountId, long offerLocationId);


// Search Offer Transactions
//
// Searches on offer transactions for offers that the account has access to.
//
list_t*
OfferAPI_searchOfferTransactionsForRetailers(apiClient_t *apiClient, double version, sirqul_iot_platform_searchOfferTransactionsForRetailers_sortField_e sortField, int *descending, int *start, int *limit, int *activeOnly, char *deviceId, long accountId, char *q, char *keyword, long retailerId, long retailerLocationId, long offerId, long offerLocationId, int *redeemed, int *reservationsOnly, sirqul_iot_platform_searchOfferTransactionsForRetailers_couponType_e couponType, sirqul_iot_platform_searchOfferTransactionsForRetailers_offerType_e offerType, sirqul_iot_platform_searchOfferTransactionsForRetailers_specialOfferType_e specialOfferType, char *customerAccountIds, char *categoryIds, long redeemableStartDate, long redeemableEndDate, int *_i, int *_l);


// Search Offers
//
// Searches for offers as a consumer.
//
offer_list_response_t*
OfferAPI_searchOffersForConsumer(apiClient_t *apiClient, double version, double latitude, double longitude, sirqul_iot_platform_searchOffersForConsumer_recommendationType_e recommendationType, long locationId, int *start, int *limit, int *maxRecommendations, sirqul_iot_platform_searchOffersForConsumer_distanceUnit_e distanceUnit, char *appKey, char *deviceId, long accountId, double searchRange, char *tags, char *supportedPostalCodes, char *keyword, char *categories, char *filters, char *offerTypes, char *type, char *sortField, char *recommendOfferIds, char *retailerLocationIds, long offerId, int *includeMission, int *includeCategories, int *includeFilters, int *includeExpired, int *includeFavorite, int *closestOfferOnly, char *searchExpression, sirqul_iot_platform_searchOffersForConsumer_groupBy_e groupBy);


// Get Offers (Top)
//
// Gets the top active offers.
//
offer_list_response_t*
OfferAPI_topOfferTransactions(apiClient_t *apiClient, double version, int *start, int *limit);


// Update Offer
//
// Update an offer, must provide a current list of retailer locations or the current offer locations will be marked as deleted.
//
retailer_offer_response_t*
OfferAPI_updateOffer(apiClient_t *apiClient, double version, long offerId, int *includeOfferLocations, char *deviceId, long accountId, long parentOfferId, char *retailerLocationIds, char *offerLocations, char *tags, char *title, char *subTitle, char *details, char *subDetails, char *finePrint, sirqul_iot_platform_updateOffer_barcodeType_e barcodeType, char *barcodeEntry, char *externalRedeemOptions, char *externalUrl, char *externalId, char *ticketsRewardType, long ticketsReward, long activated, long expires, int *noExpiration, int *availableLimit, int *availableLimitPerUser, int *addedLimit, int *viewLimit, int *maxPrints, char *ticketPriceType, long ticketPrice, double fullPrice, double discountPrice, int *showRemaining, int *showRedeemed, int *replaced, int *featured, sirqul_iot_platform_updateOffer_offerType_e offerType, sirqul_iot_platform_updateOffer_specialOfferType_e specialOfferType, sirqul_iot_platform_updateOffer_offerVisibility_e offerVisibility, char *categoryIds, char *filterIds, int *active, long barcodeAssetId, long imageAssetId, long imageAssetId1, long imageAssetId2, long imageAssetId3, long imageAssetId4, long imageAssetId5, char *publisher, long redeemableStart, long redeemableEnd, char *brand, sirqul_iot_platform_updateOffer_productType_e productType, sirqul_iot_platform_updateOffer_conditionType_e conditionType, char *isbn, char *asin, char *catalogNumbers, char *department, char *features, double minimumPrice, double width, double height, double depth, double weight, sirqul_iot_platform_updateOffer_unit_e unit, char *studio, char *parentalRating, long publishDate, long availabilityDate, long sizeId, long listingId, sirqul_iot_platform_updateOffer_mediaType_e mediaType, int *duration, char *author, long releaseDate, char *collectionIds, int *rebootTimeHour, int *rebootTimeMinute, int *idleTimeoutInSecond, char *serialNumber, char *udid, char *deviceType, double devicePower, double deviceInterference, char *availability, char *availabilitySummary);


// Activate Offer
//
// Sets the activated date on offers. This will make offers visible for consumers.
//
sirqul_response_t*
OfferAPI_updateOfferStatus(apiClient_t *apiClient, double version, char *offerIds, int *active, char *deviceId, long accountId);


