#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/payment_request.h"
#include "../model/profile_response.h"
#include "../model/sirqul_response.h"

// Enum BIOMETRICTYPE for SecureAppAPI_createSecureApplication
typedef enum  { sirqul_iot_platform_createSecureApplication_BIOMETRICTYPE_NULL = 0, sirqul_iot_platform_createSecureApplication_BIOMETRICTYPE_FINGERPRINT, sirqul_iot_platform_createSecureApplication_BIOMETRICTYPE_IRIS, sirqul_iot_platform_createSecureApplication_BIOMETRICTYPE_FACIAL } sirqul_iot_platform_createSecureApplication_biometricType_e;

// Enum BIOMETRICPOSITION for SecureAppAPI_createSecureApplication
typedef enum  { sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_NULL = 0, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_UNKNOWN, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT_INDEX, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT_MIDDLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT_RING, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT_LITTLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT_THUMB, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT_INDEX, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT_MIDDLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT_RING, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT_LITTLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT_THUMB, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_LEFT, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION_RIGHT } sirqul_iot_platform_createSecureApplication_biometricPosition_e;

// Enum BIOMETRICPOSITION2 for SecureAppAPI_createSecureApplication
typedef enum  { sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_NULL = 0, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_UNKNOWN, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT_INDEX, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT_MIDDLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT_RING, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT_LITTLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT_THUMB, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT_INDEX, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT_MIDDLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT_RING, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT_LITTLE, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT_THUMB, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_LEFT, sirqul_iot_platform_createSecureApplication_BIOMETRICPOSITION2_RIGHT } sirqul_iot_platform_createSecureApplication_biometricPosition2_e;

// Enum BIOMETRICTYPE for SecureAppAPI_updateSecureApplication
typedef enum  { sirqul_iot_platform_updateSecureApplication_BIOMETRICTYPE_NULL = 0, sirqul_iot_platform_updateSecureApplication_BIOMETRICTYPE_FINGERPRINT, sirqul_iot_platform_updateSecureApplication_BIOMETRICTYPE_IRIS, sirqul_iot_platform_updateSecureApplication_BIOMETRICTYPE_FACIAL } sirqul_iot_platform_updateSecureApplication_biometricType_e;

// Enum BIOMETRICPOSITION for SecureAppAPI_updateSecureApplication
typedef enum  { sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_NULL = 0, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_UNKNOWN, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT_INDEX, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT_MIDDLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT_RING, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT_LITTLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT_THUMB, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT_INDEX, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT_MIDDLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT_RING, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT_LITTLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT_THUMB, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_LEFT, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION_RIGHT } sirqul_iot_platform_updateSecureApplication_biometricPosition_e;

// Enum BIOMETRICPOSITION2 for SecureAppAPI_updateSecureApplication
typedef enum  { sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_NULL = 0, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_UNKNOWN, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT_INDEX, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT_MIDDLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT_RING, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT_LITTLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT_THUMB, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT_INDEX, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT_MIDDLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT_RING, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT_LITTLE, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT_THUMB, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_LEFT, sirqul_iot_platform_updateSecureApplication_BIOMETRICPOSITION2_RIGHT } sirqul_iot_platform_updateSecureApplication_biometricPosition2_e;


// Create Secure Application
//
// Create a secure application record.
//
sirqul_response_t*
SecureAppAPI_createSecureApplication(apiClient_t *apiClient, long accountId, char *appKey, binary_t* keyCert, binary_t* trustStore, char *username, char *password, int *active, sirqul_iot_platform_createSecureApplication_biometricType_e biometricType, sirqul_iot_platform_createSecureApplication_biometricPosition_e biometricPosition, sirqul_iot_platform_createSecureApplication_biometricPosition2_e biometricPosition2);


// Delete Secure Application
//
// Delete a secure application record.
//
sirqul_response_t*
SecureAppAPI_deleteSecureApplication(apiClient_t *apiClient, long accountId, char *appKey);


// Login Clear
//
// Login via Clear.me. Creates a new account if logging in for the first time.
//
profile_response_t*
SecureAppAPI_loginSecure(apiClient_t *apiClient, char *appKey, binary_t* biometricFile, char *deviceId, binary_t* biometricFile2, int *ageRestriction, int *returnProfile, char *responseFilters, double latitude, double longitude);


// Purchase Clear
//
// Purchase via Clear.me. Creates a new account if purchasing for the first time.
//
profile_response_t*
SecureAppAPI_purchaseSecure(apiClient_t *apiClient, payment_request_t *body);


// Rest Secure Application
//
// Reset a secure application client.
//
sirqul_response_t*
SecureAppAPI_resetSecure(apiClient_t *apiClient, long accountId, char *appKey);


// Update Secure Application
//
// Update a secure application record.
//
sirqul_response_t*
SecureAppAPI_updateSecureApplication(apiClient_t *apiClient, long accountId, char *appKey, int *active, binary_t* keyCert, binary_t* trustStore, char *username, char *password, sirqul_iot_platform_updateSecureApplication_biometricType_e biometricType, sirqul_iot_platform_updateSecureApplication_biometricPosition_e biometricPosition, sirqul_iot_platform_updateSecureApplication_biometricPosition2_e biometricPosition2);


