/*
Sirqul IoT Platform

Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>

API version: 3.16
Contact: info@sirqul.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AssetShortResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetShortResponse{}

// AssetShortResponse struct for AssetShortResponse
type AssetShortResponse struct {
	Valid *bool `json:"valid,omitempty"`
	Message *string `json:"message,omitempty"`
	Version *float64 `json:"version,omitempty"`
	SerializeNulls *bool `json:"serializeNulls,omitempty"`
	StartTimeLog *int64 `json:"startTimeLog,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
	Request []NameStringValueResponse `json:"request,omitempty"`
	AssetId *int64 `json:"assetId,omitempty"`
	FileName *string `json:"fileName,omitempty"`
	Caption *string `json:"caption,omitempty"`
	MediaType *string `json:"mediaType,omitempty"`
	ThumbnailURL *string `json:"thumbnailURL,omitempty"`
	CoverURL *string `json:"coverURL,omitempty"`
	FullURL *string `json:"fullURL,omitempty"`
	AssetVersion *string `json:"assetVersion,omitempty"`
	VersionName *string `json:"versionName,omitempty"`
	VersionCode *int32 `json:"versionCode,omitempty"`
	Returning *string `json:"returning,omitempty"`
}

// NewAssetShortResponse instantiates a new AssetShortResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetShortResponse() *AssetShortResponse {
	this := AssetShortResponse{}
	return &this
}

// NewAssetShortResponseWithDefaults instantiates a new AssetShortResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetShortResponseWithDefaults() *AssetShortResponse {
	this := AssetShortResponse{}
	return &this
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *AssetShortResponse) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *AssetShortResponse) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *AssetShortResponse) SetValid(v bool) {
	o.Valid = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AssetShortResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AssetShortResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AssetShortResponse) SetMessage(v string) {
	o.Message = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AssetShortResponse) GetVersion() float64 {
	if o == nil || IsNil(o.Version) {
		var ret float64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetVersionOk() (*float64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AssetShortResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given float64 and assigns it to the Version field.
func (o *AssetShortResponse) SetVersion(v float64) {
	o.Version = &v
}

// GetSerializeNulls returns the SerializeNulls field value if set, zero value otherwise.
func (o *AssetShortResponse) GetSerializeNulls() bool {
	if o == nil || IsNil(o.SerializeNulls) {
		var ret bool
		return ret
	}
	return *o.SerializeNulls
}

// GetSerializeNullsOk returns a tuple with the SerializeNulls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetSerializeNullsOk() (*bool, bool) {
	if o == nil || IsNil(o.SerializeNulls) {
		return nil, false
	}
	return o.SerializeNulls, true
}

// HasSerializeNulls returns a boolean if a field has been set.
func (o *AssetShortResponse) HasSerializeNulls() bool {
	if o != nil && !IsNil(o.SerializeNulls) {
		return true
	}

	return false
}

// SetSerializeNulls gets a reference to the given bool and assigns it to the SerializeNulls field.
func (o *AssetShortResponse) SetSerializeNulls(v bool) {
	o.SerializeNulls = &v
}

// GetStartTimeLog returns the StartTimeLog field value if set, zero value otherwise.
func (o *AssetShortResponse) GetStartTimeLog() int64 {
	if o == nil || IsNil(o.StartTimeLog) {
		var ret int64
		return ret
	}
	return *o.StartTimeLog
}

// GetStartTimeLogOk returns a tuple with the StartTimeLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetStartTimeLogOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTimeLog) {
		return nil, false
	}
	return o.StartTimeLog, true
}

// HasStartTimeLog returns a boolean if a field has been set.
func (o *AssetShortResponse) HasStartTimeLog() bool {
	if o != nil && !IsNil(o.StartTimeLog) {
		return true
	}

	return false
}

// SetStartTimeLog gets a reference to the given int64 and assigns it to the StartTimeLog field.
func (o *AssetShortResponse) SetStartTimeLog(v int64) {
	o.StartTimeLog = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *AssetShortResponse) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AssetShortResponse) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *AssetShortResponse) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *AssetShortResponse) GetRequest() []NameStringValueResponse {
	if o == nil || IsNil(o.Request) {
		var ret []NameStringValueResponse
		return ret
	}
	return o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetRequestOk() ([]NameStringValueResponse, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *AssetShortResponse) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given []NameStringValueResponse and assigns it to the Request field.
func (o *AssetShortResponse) SetRequest(v []NameStringValueResponse) {
	o.Request = v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *AssetShortResponse) GetAssetId() int64 {
	if o == nil || IsNil(o.AssetId) {
		var ret int64
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetAssetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *AssetShortResponse) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given int64 and assigns it to the AssetId field.
func (o *AssetShortResponse) SetAssetId(v int64) {
	o.AssetId = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *AssetShortResponse) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *AssetShortResponse) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *AssetShortResponse) SetFileName(v string) {
	o.FileName = &v
}

// GetCaption returns the Caption field value if set, zero value otherwise.
func (o *AssetShortResponse) GetCaption() string {
	if o == nil || IsNil(o.Caption) {
		var ret string
		return ret
	}
	return *o.Caption
}

// GetCaptionOk returns a tuple with the Caption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetCaptionOk() (*string, bool) {
	if o == nil || IsNil(o.Caption) {
		return nil, false
	}
	return o.Caption, true
}

// HasCaption returns a boolean if a field has been set.
func (o *AssetShortResponse) HasCaption() bool {
	if o != nil && !IsNil(o.Caption) {
		return true
	}

	return false
}

// SetCaption gets a reference to the given string and assigns it to the Caption field.
func (o *AssetShortResponse) SetCaption(v string) {
	o.Caption = &v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *AssetShortResponse) GetMediaType() string {
	if o == nil || IsNil(o.MediaType) {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetMediaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaType) {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *AssetShortResponse) HasMediaType() bool {
	if o != nil && !IsNil(o.MediaType) {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *AssetShortResponse) SetMediaType(v string) {
	o.MediaType = &v
}

// GetThumbnailURL returns the ThumbnailURL field value if set, zero value otherwise.
func (o *AssetShortResponse) GetThumbnailURL() string {
	if o == nil || IsNil(o.ThumbnailURL) {
		var ret string
		return ret
	}
	return *o.ThumbnailURL
}

// GetThumbnailURLOk returns a tuple with the ThumbnailURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetThumbnailURLOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailURL) {
		return nil, false
	}
	return o.ThumbnailURL, true
}

// HasThumbnailURL returns a boolean if a field has been set.
func (o *AssetShortResponse) HasThumbnailURL() bool {
	if o != nil && !IsNil(o.ThumbnailURL) {
		return true
	}

	return false
}

// SetThumbnailURL gets a reference to the given string and assigns it to the ThumbnailURL field.
func (o *AssetShortResponse) SetThumbnailURL(v string) {
	o.ThumbnailURL = &v
}

// GetCoverURL returns the CoverURL field value if set, zero value otherwise.
func (o *AssetShortResponse) GetCoverURL() string {
	if o == nil || IsNil(o.CoverURL) {
		var ret string
		return ret
	}
	return *o.CoverURL
}

// GetCoverURLOk returns a tuple with the CoverURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetCoverURLOk() (*string, bool) {
	if o == nil || IsNil(o.CoverURL) {
		return nil, false
	}
	return o.CoverURL, true
}

// HasCoverURL returns a boolean if a field has been set.
func (o *AssetShortResponse) HasCoverURL() bool {
	if o != nil && !IsNil(o.CoverURL) {
		return true
	}

	return false
}

// SetCoverURL gets a reference to the given string and assigns it to the CoverURL field.
func (o *AssetShortResponse) SetCoverURL(v string) {
	o.CoverURL = &v
}

// GetFullURL returns the FullURL field value if set, zero value otherwise.
func (o *AssetShortResponse) GetFullURL() string {
	if o == nil || IsNil(o.FullURL) {
		var ret string
		return ret
	}
	return *o.FullURL
}

// GetFullURLOk returns a tuple with the FullURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetFullURLOk() (*string, bool) {
	if o == nil || IsNil(o.FullURL) {
		return nil, false
	}
	return o.FullURL, true
}

// HasFullURL returns a boolean if a field has been set.
func (o *AssetShortResponse) HasFullURL() bool {
	if o != nil && !IsNil(o.FullURL) {
		return true
	}

	return false
}

// SetFullURL gets a reference to the given string and assigns it to the FullURL field.
func (o *AssetShortResponse) SetFullURL(v string) {
	o.FullURL = &v
}

// GetAssetVersion returns the AssetVersion field value if set, zero value otherwise.
func (o *AssetShortResponse) GetAssetVersion() string {
	if o == nil || IsNil(o.AssetVersion) {
		var ret string
		return ret
	}
	return *o.AssetVersion
}

// GetAssetVersionOk returns a tuple with the AssetVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetAssetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AssetVersion) {
		return nil, false
	}
	return o.AssetVersion, true
}

// HasAssetVersion returns a boolean if a field has been set.
func (o *AssetShortResponse) HasAssetVersion() bool {
	if o != nil && !IsNil(o.AssetVersion) {
		return true
	}

	return false
}

// SetAssetVersion gets a reference to the given string and assigns it to the AssetVersion field.
func (o *AssetShortResponse) SetAssetVersion(v string) {
	o.AssetVersion = &v
}

// GetVersionName returns the VersionName field value if set, zero value otherwise.
func (o *AssetShortResponse) GetVersionName() string {
	if o == nil || IsNil(o.VersionName) {
		var ret string
		return ret
	}
	return *o.VersionName
}

// GetVersionNameOk returns a tuple with the VersionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetVersionNameOk() (*string, bool) {
	if o == nil || IsNil(o.VersionName) {
		return nil, false
	}
	return o.VersionName, true
}

// HasVersionName returns a boolean if a field has been set.
func (o *AssetShortResponse) HasVersionName() bool {
	if o != nil && !IsNil(o.VersionName) {
		return true
	}

	return false
}

// SetVersionName gets a reference to the given string and assigns it to the VersionName field.
func (o *AssetShortResponse) SetVersionName(v string) {
	o.VersionName = &v
}

// GetVersionCode returns the VersionCode field value if set, zero value otherwise.
func (o *AssetShortResponse) GetVersionCode() int32 {
	if o == nil || IsNil(o.VersionCode) {
		var ret int32
		return ret
	}
	return *o.VersionCode
}

// GetVersionCodeOk returns a tuple with the VersionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetVersionCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.VersionCode) {
		return nil, false
	}
	return o.VersionCode, true
}

// HasVersionCode returns a boolean if a field has been set.
func (o *AssetShortResponse) HasVersionCode() bool {
	if o != nil && !IsNil(o.VersionCode) {
		return true
	}

	return false
}

// SetVersionCode gets a reference to the given int32 and assigns it to the VersionCode field.
func (o *AssetShortResponse) SetVersionCode(v int32) {
	o.VersionCode = &v
}

// GetReturning returns the Returning field value if set, zero value otherwise.
func (o *AssetShortResponse) GetReturning() string {
	if o == nil || IsNil(o.Returning) {
		var ret string
		return ret
	}
	return *o.Returning
}

// GetReturningOk returns a tuple with the Returning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetShortResponse) GetReturningOk() (*string, bool) {
	if o == nil || IsNil(o.Returning) {
		return nil, false
	}
	return o.Returning, true
}

// HasReturning returns a boolean if a field has been set.
func (o *AssetShortResponse) HasReturning() bool {
	if o != nil && !IsNil(o.Returning) {
		return true
	}

	return false
}

// SetReturning gets a reference to the given string and assigns it to the Returning field.
func (o *AssetShortResponse) SetReturning(v string) {
	o.Returning = &v
}

func (o AssetShortResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetShortResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.SerializeNulls) {
		toSerialize["serializeNulls"] = o.SerializeNulls
	}
	if !IsNil(o.StartTimeLog) {
		toSerialize["startTimeLog"] = o.StartTimeLog
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.AssetId) {
		toSerialize["assetId"] = o.AssetId
	}
	if !IsNil(o.FileName) {
		toSerialize["fileName"] = o.FileName
	}
	if !IsNil(o.Caption) {
		toSerialize["caption"] = o.Caption
	}
	if !IsNil(o.MediaType) {
		toSerialize["mediaType"] = o.MediaType
	}
	if !IsNil(o.ThumbnailURL) {
		toSerialize["thumbnailURL"] = o.ThumbnailURL
	}
	if !IsNil(o.CoverURL) {
		toSerialize["coverURL"] = o.CoverURL
	}
	if !IsNil(o.FullURL) {
		toSerialize["fullURL"] = o.FullURL
	}
	if !IsNil(o.AssetVersion) {
		toSerialize["assetVersion"] = o.AssetVersion
	}
	if !IsNil(o.VersionName) {
		toSerialize["versionName"] = o.VersionName
	}
	if !IsNil(o.VersionCode) {
		toSerialize["versionCode"] = o.VersionCode
	}
	if !IsNil(o.Returning) {
		toSerialize["returning"] = o.Returning
	}
	return toSerialize, nil
}

type NullableAssetShortResponse struct {
	value *AssetShortResponse
	isSet bool
}

func (v NullableAssetShortResponse) Get() *AssetShortResponse {
	return v.value
}

func (v *NullableAssetShortResponse) Set(val *AssetShortResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetShortResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetShortResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetShortResponse(val *AssetShortResponse) *NullableAssetShortResponse {
	return &NullableAssetShortResponse{value: val, isSet: true}
}

func (v NullableAssetShortResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetShortResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


