/*
Sirqul IoT Platform

Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>

API version: 3.16
Contact: info@sirqul.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreativeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreativeResponse{}

// CreativeResponse struct for CreativeResponse
type CreativeResponse struct {
	CreativeId *int64 `json:"creativeId,omitempty"`
	Active *bool `json:"active,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Image *AssetShortResponse `json:"image,omitempty"`
	Action *string `json:"action,omitempty"`
	Content *JsonElement `json:"content,omitempty"`
	Suffix *string `json:"suffix,omitempty"`
	Type *string `json:"type,omitempty"`
	AppVersion *string `json:"appVersion,omitempty"`
	Preview *bool `json:"preview,omitempty"`
	Owner *AccountShortResponse `json:"owner,omitempty"`
	CurrentBid *BidResponse `json:"currentBid,omitempty"`
}

// NewCreativeResponse instantiates a new CreativeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreativeResponse() *CreativeResponse {
	this := CreativeResponse{}
	return &this
}

// NewCreativeResponseWithDefaults instantiates a new CreativeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreativeResponseWithDefaults() *CreativeResponse {
	this := CreativeResponse{}
	return &this
}

// GetCreativeId returns the CreativeId field value if set, zero value otherwise.
func (o *CreativeResponse) GetCreativeId() int64 {
	if o == nil || IsNil(o.CreativeId) {
		var ret int64
		return ret
	}
	return *o.CreativeId
}

// GetCreativeIdOk returns a tuple with the CreativeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetCreativeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CreativeId) {
		return nil, false
	}
	return o.CreativeId, true
}

// HasCreativeId returns a boolean if a field has been set.
func (o *CreativeResponse) HasCreativeId() bool {
	if o != nil && !IsNil(o.CreativeId) {
		return true
	}

	return false
}

// SetCreativeId gets a reference to the given int64 and assigns it to the CreativeId field.
func (o *CreativeResponse) SetCreativeId(v int64) {
	o.CreativeId = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CreativeResponse) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CreativeResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CreativeResponse) SetActive(v bool) {
	o.Active = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreativeResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreativeResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreativeResponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreativeResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreativeResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreativeResponse) SetDescription(v string) {
	o.Description = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *CreativeResponse) GetImage() AssetShortResponse {
	if o == nil || IsNil(o.Image) {
		var ret AssetShortResponse
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetImageOk() (*AssetShortResponse, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *CreativeResponse) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given AssetShortResponse and assigns it to the Image field.
func (o *CreativeResponse) SetImage(v AssetShortResponse) {
	o.Image = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *CreativeResponse) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *CreativeResponse) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *CreativeResponse) SetAction(v string) {
	o.Action = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CreativeResponse) GetContent() JsonElement {
	if o == nil || IsNil(o.Content) {
		var ret JsonElement
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetContentOk() (*JsonElement, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CreativeResponse) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given JsonElement and assigns it to the Content field.
func (o *CreativeResponse) SetContent(v JsonElement) {
	o.Content = &v
}

// GetSuffix returns the Suffix field value if set, zero value otherwise.
func (o *CreativeResponse) GetSuffix() string {
	if o == nil || IsNil(o.Suffix) {
		var ret string
		return ret
	}
	return *o.Suffix
}

// GetSuffixOk returns a tuple with the Suffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetSuffixOk() (*string, bool) {
	if o == nil || IsNil(o.Suffix) {
		return nil, false
	}
	return o.Suffix, true
}

// HasSuffix returns a boolean if a field has been set.
func (o *CreativeResponse) HasSuffix() bool {
	if o != nil && !IsNil(o.Suffix) {
		return true
	}

	return false
}

// SetSuffix gets a reference to the given string and assigns it to the Suffix field.
func (o *CreativeResponse) SetSuffix(v string) {
	o.Suffix = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreativeResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreativeResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreativeResponse) SetType(v string) {
	o.Type = &v
}

// GetAppVersion returns the AppVersion field value if set, zero value otherwise.
func (o *CreativeResponse) GetAppVersion() string {
	if o == nil || IsNil(o.AppVersion) {
		var ret string
		return ret
	}
	return *o.AppVersion
}

// GetAppVersionOk returns a tuple with the AppVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetAppVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AppVersion) {
		return nil, false
	}
	return o.AppVersion, true
}

// HasAppVersion returns a boolean if a field has been set.
func (o *CreativeResponse) HasAppVersion() bool {
	if o != nil && !IsNil(o.AppVersion) {
		return true
	}

	return false
}

// SetAppVersion gets a reference to the given string and assigns it to the AppVersion field.
func (o *CreativeResponse) SetAppVersion(v string) {
	o.AppVersion = &v
}

// GetPreview returns the Preview field value if set, zero value otherwise.
func (o *CreativeResponse) GetPreview() bool {
	if o == nil || IsNil(o.Preview) {
		var ret bool
		return ret
	}
	return *o.Preview
}

// GetPreviewOk returns a tuple with the Preview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetPreviewOk() (*bool, bool) {
	if o == nil || IsNil(o.Preview) {
		return nil, false
	}
	return o.Preview, true
}

// HasPreview returns a boolean if a field has been set.
func (o *CreativeResponse) HasPreview() bool {
	if o != nil && !IsNil(o.Preview) {
		return true
	}

	return false
}

// SetPreview gets a reference to the given bool and assigns it to the Preview field.
func (o *CreativeResponse) SetPreview(v bool) {
	o.Preview = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *CreativeResponse) GetOwner() AccountShortResponse {
	if o == nil || IsNil(o.Owner) {
		var ret AccountShortResponse
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetOwnerOk() (*AccountShortResponse, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *CreativeResponse) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given AccountShortResponse and assigns it to the Owner field.
func (o *CreativeResponse) SetOwner(v AccountShortResponse) {
	o.Owner = &v
}

// GetCurrentBid returns the CurrentBid field value if set, zero value otherwise.
func (o *CreativeResponse) GetCurrentBid() BidResponse {
	if o == nil || IsNil(o.CurrentBid) {
		var ret BidResponse
		return ret
	}
	return *o.CurrentBid
}

// GetCurrentBidOk returns a tuple with the CurrentBid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeResponse) GetCurrentBidOk() (*BidResponse, bool) {
	if o == nil || IsNil(o.CurrentBid) {
		return nil, false
	}
	return o.CurrentBid, true
}

// HasCurrentBid returns a boolean if a field has been set.
func (o *CreativeResponse) HasCurrentBid() bool {
	if o != nil && !IsNil(o.CurrentBid) {
		return true
	}

	return false
}

// SetCurrentBid gets a reference to the given BidResponse and assigns it to the CurrentBid field.
func (o *CreativeResponse) SetCurrentBid(v BidResponse) {
	o.CurrentBid = &v
}

func (o CreativeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreativeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreativeId) {
		toSerialize["creativeId"] = o.CreativeId
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Suffix) {
		toSerialize["suffix"] = o.Suffix
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.AppVersion) {
		toSerialize["appVersion"] = o.AppVersion
	}
	if !IsNil(o.Preview) {
		toSerialize["preview"] = o.Preview
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.CurrentBid) {
		toSerialize["currentBid"] = o.CurrentBid
	}
	return toSerialize, nil
}

type NullableCreativeResponse struct {
	value *CreativeResponse
	isSet bool
}

func (v NullableCreativeResponse) Get() *CreativeResponse {
	return v.value
}

func (v *NullableCreativeResponse) Set(val *CreativeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreativeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreativeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreativeResponse(val *CreativeResponse) *NullableCreativeResponse {
	return &NullableCreativeResponse{value: val, isSet: true}
}

func (v NullableCreativeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreativeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


