/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/MessageResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

MessageResponse::MessageResponse()
{
    m_Message = utility::conversions::to_string_t("");
    m_MessageIsSet = false;
    m_Code = 0;
    m_CodeIsSet = false;
    m_Ids = utility::conversions::to_string_t("");
    m_IdsIsSet = false;
    m_UpdateValue = utility::conversions::to_string_t("");
    m_UpdateValueIsSet = false;
}

MessageResponse::~MessageResponse()
{
}

void MessageResponse::validate()
{
    // TODO: implement validation
}

web::json::value MessageResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_MessageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("message"))] = ModelBase::toJson(m_Message);
    }
    if(m_CodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_IdsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("ids"))] = ModelBase::toJson(m_Ids);
    }
    if(m_UpdateValueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updateValue"))] = ModelBase::toJson(m_UpdateValue);
    }

    return val;
}

bool MessageResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessage);
            setMessage(refVal_setMessage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ids"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ids")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIds);
            setIds(refVal_setIds);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updateValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updateValue")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdateValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdateValue);
            setUpdateValue(refVal_setUpdateValue);
            
        }
    }
    return ok;
}

void MessageResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_MessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("message")), m_Message));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_IdsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ids")), m_Ids));
    }
    if(m_UpdateValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updateValue")), m_UpdateValue));
    }
}

bool MessageResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        utility::string_t refVal_setMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("message"))), refVal_setMessage );
        setMessage(refVal_setMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        int32_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ids"))))
    {
        utility::string_t refVal_setIds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ids"))), refVal_setIds );
        setIds(refVal_setIds);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updateValue"))))
    {
        utility::string_t refVal_setUpdateValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updateValue"))), refVal_setUpdateValue );
        setUpdateValue(refVal_setUpdateValue);
    }
    return ok;
}


utility::string_t MessageResponse::getMessage() const
{
    return m_Message;
}


void MessageResponse::setMessage(const utility::string_t& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}

bool MessageResponse::messageIsSet() const
{
    return m_MessageIsSet;
}

void MessageResponse::unsetMessage()
{
    m_MessageIsSet = false;
}
int32_t MessageResponse::getCode() const
{
    return m_Code;
}

void MessageResponse::setCode(int32_t value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool MessageResponse::codeIsSet() const
{
    return m_CodeIsSet;
}

void MessageResponse::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t MessageResponse::getIds() const
{
    return m_Ids;
}


void MessageResponse::setIds(const utility::string_t& value)
{
    m_Ids = value;
    m_IdsIsSet = true;
}

bool MessageResponse::idsIsSet() const
{
    return m_IdsIsSet;
}

void MessageResponse::unsetIds()
{
    m_IdsIsSet = false;
}
utility::string_t MessageResponse::getUpdateValue() const
{
    return m_UpdateValue;
}


void MessageResponse::setUpdateValue(const utility::string_t& value)
{
    m_UpdateValue = value;
    m_UpdateValueIsSet = true;
}

bool MessageResponse::updateValueIsSet() const
{
    return m_UpdateValueIsSet;
}

void MessageResponse::unsetUpdateValue()
{
    m_UpdateValueIsSet = false;
}

}
}
}
}


