/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RewardResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RewardResponse::RewardResponse()
{
    m_OfferId = 0L;
    m_OfferIdIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_SubTitle = utility::conversions::to_string_t("");
    m_SubTitleIsSet = false;
    m_Details = utility::conversions::to_string_t("");
    m_DetailsIsSet = false;
    m_ArtworkIsSet = false;
    m_FinePrint = utility::conversions::to_string_t("");
    m_FinePrintIsSet = false;
    m_RedemptionCode = utility::conversions::to_string_t("");
    m_RedemptionCodeIsSet = false;
    m_RedemptionStatus = 0;
    m_RedemptionStatusIsSet = false;
    m_TransactionId = 0L;
    m_TransactionIdIsSet = false;
    m_EstimatedValue = 0.0;
    m_EstimatedValueIsSet = false;
}

RewardResponse::~RewardResponse()
{
}

void RewardResponse::validate()
{
    // TODO: implement validation
}

web::json::value RewardResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_OfferIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("offerId"))] = ModelBase::toJson(m_OfferId);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_SubTitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subTitle"))] = ModelBase::toJson(m_SubTitle);
    }
    if(m_DetailsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("details"))] = ModelBase::toJson(m_Details);
    }
    if(m_ArtworkIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("artwork"))] = ModelBase::toJson(m_Artwork);
    }
    if(m_FinePrintIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("finePrint"))] = ModelBase::toJson(m_FinePrint);
    }
    if(m_RedemptionCodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("redemptionCode"))] = ModelBase::toJson(m_RedemptionCode);
    }
    if(m_RedemptionStatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("redemptionStatus"))] = ModelBase::toJson(m_RedemptionStatus);
    }
    if(m_TransactionIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("transactionId"))] = ModelBase::toJson(m_TransactionId);
    }
    if(m_EstimatedValueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("estimatedValue"))] = ModelBase::toJson(m_EstimatedValue);
    }

    return val;
}

bool RewardResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("offerId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("offerId")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setOfferId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOfferId);
            setOfferId(refVal_setOfferId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subTitle"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subTitle")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubTitle);
            setSubTitle(refVal_setSubTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("details"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("details")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDetails;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDetails);
            setDetails(refVal_setDetails);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("artwork"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("artwork")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AssetShortResponse> refVal_setArtwork;
            ok &= ModelBase::fromJson(fieldValue, refVal_setArtwork);
            setArtwork(refVal_setArtwork);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("finePrint"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("finePrint")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFinePrint;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFinePrint);
            setFinePrint(refVal_setFinePrint);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("redemptionCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("redemptionCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRedemptionCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRedemptionCode);
            setRedemptionCode(refVal_setRedemptionCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("redemptionStatus"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("redemptionStatus")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRedemptionStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRedemptionStatus);
            setRedemptionStatus(refVal_setRedemptionStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("transactionId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("transactionId")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTransactionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTransactionId);
            setTransactionId(refVal_setTransactionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("estimatedValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("estimatedValue")));
        if(!fieldValue.is_null())
        {
            double refVal_setEstimatedValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEstimatedValue);
            setEstimatedValue(refVal_setEstimatedValue);
            
        }
    }
    return ok;
}

void RewardResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_OfferIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("offerId")), m_OfferId));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_SubTitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subTitle")), m_SubTitle));
    }
    if(m_DetailsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("details")), m_Details));
    }
    if(m_ArtworkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("artwork")), m_Artwork));
    }
    if(m_FinePrintIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("finePrint")), m_FinePrint));
    }
    if(m_RedemptionCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("redemptionCode")), m_RedemptionCode));
    }
    if(m_RedemptionStatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("redemptionStatus")), m_RedemptionStatus));
    }
    if(m_TransactionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("transactionId")), m_TransactionId));
    }
    if(m_EstimatedValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("estimatedValue")), m_EstimatedValue));
    }
}

bool RewardResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("offerId"))))
    {
        int64_t refVal_setOfferId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("offerId"))), refVal_setOfferId );
        setOfferId(refVal_setOfferId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subTitle"))))
    {
        utility::string_t refVal_setSubTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subTitle"))), refVal_setSubTitle );
        setSubTitle(refVal_setSubTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("details"))))
    {
        utility::string_t refVal_setDetails;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("details"))), refVal_setDetails );
        setDetails(refVal_setDetails);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("artwork"))))
    {
        std::shared_ptr<AssetShortResponse> refVal_setArtwork;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("artwork"))), refVal_setArtwork );
        setArtwork(refVal_setArtwork);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("finePrint"))))
    {
        utility::string_t refVal_setFinePrint;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("finePrint"))), refVal_setFinePrint );
        setFinePrint(refVal_setFinePrint);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("redemptionCode"))))
    {
        utility::string_t refVal_setRedemptionCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("redemptionCode"))), refVal_setRedemptionCode );
        setRedemptionCode(refVal_setRedemptionCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("redemptionStatus"))))
    {
        int32_t refVal_setRedemptionStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("redemptionStatus"))), refVal_setRedemptionStatus );
        setRedemptionStatus(refVal_setRedemptionStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("transactionId"))))
    {
        int64_t refVal_setTransactionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("transactionId"))), refVal_setTransactionId );
        setTransactionId(refVal_setTransactionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("estimatedValue"))))
    {
        double refVal_setEstimatedValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("estimatedValue"))), refVal_setEstimatedValue );
        setEstimatedValue(refVal_setEstimatedValue);
    }
    return ok;
}


int64_t RewardResponse::getOfferId() const
{
    return m_OfferId;
}

void RewardResponse::setOfferId(int64_t value)
{
    m_OfferId = value;
    m_OfferIdIsSet = true;
}

bool RewardResponse::offerIdIsSet() const
{
    return m_OfferIdIsSet;
}

void RewardResponse::unsetOfferId()
{
    m_OfferIdIsSet = false;
}
utility::string_t RewardResponse::getTitle() const
{
    return m_Title;
}


void RewardResponse::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool RewardResponse::titleIsSet() const
{
    return m_TitleIsSet;
}

void RewardResponse::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t RewardResponse::getSubTitle() const
{
    return m_SubTitle;
}


void RewardResponse::setSubTitle(const utility::string_t& value)
{
    m_SubTitle = value;
    m_SubTitleIsSet = true;
}

bool RewardResponse::subTitleIsSet() const
{
    return m_SubTitleIsSet;
}

void RewardResponse::unsetSubTitle()
{
    m_SubTitleIsSet = false;
}
utility::string_t RewardResponse::getDetails() const
{
    return m_Details;
}


void RewardResponse::setDetails(const utility::string_t& value)
{
    m_Details = value;
    m_DetailsIsSet = true;
}

bool RewardResponse::detailsIsSet() const
{
    return m_DetailsIsSet;
}

void RewardResponse::unsetDetails()
{
    m_DetailsIsSet = false;
}
std::shared_ptr<AssetShortResponse> RewardResponse::getArtwork() const
{
    return m_Artwork;
}


void RewardResponse::setArtwork(const std::shared_ptr<AssetShortResponse>& value)
{
    m_Artwork = value;
    m_ArtworkIsSet = true;
}

bool RewardResponse::artworkIsSet() const
{
    return m_ArtworkIsSet;
}

void RewardResponse::unsetArtwork()
{
    m_ArtworkIsSet = false;
}
utility::string_t RewardResponse::getFinePrint() const
{
    return m_FinePrint;
}


void RewardResponse::setFinePrint(const utility::string_t& value)
{
    m_FinePrint = value;
    m_FinePrintIsSet = true;
}

bool RewardResponse::finePrintIsSet() const
{
    return m_FinePrintIsSet;
}

void RewardResponse::unsetFinePrint()
{
    m_FinePrintIsSet = false;
}
utility::string_t RewardResponse::getRedemptionCode() const
{
    return m_RedemptionCode;
}


void RewardResponse::setRedemptionCode(const utility::string_t& value)
{
    m_RedemptionCode = value;
    m_RedemptionCodeIsSet = true;
}

bool RewardResponse::redemptionCodeIsSet() const
{
    return m_RedemptionCodeIsSet;
}

void RewardResponse::unsetRedemptionCode()
{
    m_RedemptionCodeIsSet = false;
}
int32_t RewardResponse::getRedemptionStatus() const
{
    return m_RedemptionStatus;
}

void RewardResponse::setRedemptionStatus(int32_t value)
{
    m_RedemptionStatus = value;
    m_RedemptionStatusIsSet = true;
}

bool RewardResponse::redemptionStatusIsSet() const
{
    return m_RedemptionStatusIsSet;
}

void RewardResponse::unsetRedemptionStatus()
{
    m_RedemptionStatusIsSet = false;
}
int64_t RewardResponse::getTransactionId() const
{
    return m_TransactionId;
}

void RewardResponse::setTransactionId(int64_t value)
{
    m_TransactionId = value;
    m_TransactionIdIsSet = true;
}

bool RewardResponse::transactionIdIsSet() const
{
    return m_TransactionIdIsSet;
}

void RewardResponse::unsetTransactionId()
{
    m_TransactionIdIsSet = false;
}
double RewardResponse::getEstimatedValue() const
{
    return m_EstimatedValue;
}

void RewardResponse::setEstimatedValue(double value)
{
    m_EstimatedValue = value;
    m_EstimatedValueIsSet = true;
}

bool RewardResponse::estimatedValueIsSet() const
{
    return m_EstimatedValueIsSet;
}

void RewardResponse::unsetEstimatedValue()
{
    m_EstimatedValueIsSet = false;
}

}
}
}
}


