#' Sirqul IoT Platform
#'
#' Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
#'
#' The version of the OpenAPI document: 3.16
#' Contact: info@sirqul.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Workflow operations
#' @description WorkflowApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  RunWorkflow  ####################
#'
#' library(openapi)
#' var_account_id <- 56 # integer | the account ID of the user
#' var_workflow_id <- 56 # integer | the workflow to run
#' var_sku_id <- 56 # integer | this runs a particular sku on the workflow (Optional)
#' var_version_code <- 56 # integer | this runs a particular sku version on the workflow (Optional)
#' var_parameters <- "parameters_example" # character | Override parameters in JSON format. Example: ```json {   \"arguments_81\": { \"filter\": \"PUBLIC\" },   \"arguments_87\": { \"tag\": \"custom_tag\" } } ```  (Optional)
#'
#' #Run Workflow
#' api_instance <- WorkflowApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$RunWorkflow(var_account_id, var_workflow_id, sku_id = var_sku_id, version_code = var_version_code, parameters = var_parametersdata_file = "result.txt")
#' result <- api_instance$RunWorkflow(var_account_id, var_workflow_id, sku_id = var_sku_id, version_code = var_version_code, parameters = var_parameters)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
WorkflowApi <- R6::R6Class(
  "WorkflowApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new WorkflowApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Run Workflow
    #'
    #' @param account_id the account ID of the user
    #' @param workflow_id the workflow to run
    #' @param sku_id (optional) this runs a particular sku on the workflow
    #' @param version_code (optional) this runs a particular sku version on the workflow
    #' @param parameters (optional) Override parameters in JSON format. Example: ```json {   \"arguments_81\": { \"filter\": \"PUBLIC\" },   \"arguments_87\": { \"tag\": \"custom_tag\" } } ``` 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return SirqulResponse
    RunWorkflow = function(account_id, workflow_id, sku_id = NULL, version_code = NULL, parameters = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$RunWorkflowWithHttpInfo(account_id, workflow_id, sku_id, version_code, parameters, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Run Workflow
    #'
    #' @param account_id the account ID of the user
    #' @param workflow_id the workflow to run
    #' @param sku_id (optional) this runs a particular sku on the workflow
    #' @param version_code (optional) this runs a particular sku version on the workflow
    #' @param parameters (optional) Override parameters in JSON format. Example: ```json {   \"arguments_81\": { \"filter\": \"PUBLIC\" },   \"arguments_87\": { \"tag\": \"custom_tag\" } } ``` 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (SirqulResponse) with additional information such as HTTP status code, headers
    RunWorkflowWithHttpInfo = function(account_id, workflow_id, sku_id = NULL, version_code = NULL, parameters = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`account_id`)) {
        stop("Missing required parameter `account_id`.")
      }

      if (missing(`workflow_id`)) {
        stop("Missing required parameter `workflow_id`.")
      }

      if (!missing(`account_id`) && is.null(`account_id`)) {
        stop("Invalid value for `account_id` when calling WorkflowApi$RunWorkflow, `account_id` is not nullable")
      }

      if (!missing(`workflow_id`) && is.null(`workflow_id`)) {
        stop("Invalid value for `workflow_id` when calling WorkflowApi$RunWorkflow, `workflow_id` is not nullable")
      }

      if (!missing(`sku_id`) && is.null(`sku_id`)) {
        stop("Invalid value for `sku_id` when calling WorkflowApi$RunWorkflow, `sku_id` is not nullable")
      }

      if (!missing(`version_code`) && is.null(`version_code`)) {
        stop("Invalid value for `version_code` when calling WorkflowApi$RunWorkflow, `version_code` is not nullable")
      }

      if (!missing(`parameters`) && is.null(`parameters`)) {
        stop("Invalid value for `parameters` when calling WorkflowApi$RunWorkflow, `parameters` is not nullable")
      }

      query_params[["accountId"]] <- `account_id`

      query_params[["workflowId"]] <- `workflow_id`

      query_params[["skuId"]] <- `sku_id`

      query_params[["versionCode"]] <- `version_code`

      query_params[["parameters"]] <- `parameters`

      local_var_url_path <- "/workflow/run"

      # The Accept request HTTP header
      local_var_accepts <- list("*/*")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "SirqulResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
