extends Resource
class_name Platform

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# Platform Model


# Required: False
# isArray: false
@export var id: float:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Required: False
# isArray: false
@export var active: bool:
	set(value):
		__active__was__set = true
		active = value
var __active__was__set := false

# Required: False
# isArray: false
@export var valid: bool:
	set(value):
		__valid__was__set = true
		valid = value
var __valid__was__set := false

# Required: False
# isArray: false
@export var device: AudienceDevice:
	set(value):
		__device__was__set = true
		device = value
var __device__was__set := false

# Required: False
# isArray: false
@export var minimum: float:
	set(value):
		__minimum__was__set = true
		minimum = value
var __minimum__was__set := false

# Required: False
# isArray: false
@export var maximum: float:
	set(value):
		__maximum__was__set = true
		maximum = value
var __maximum__was__set := false

# Required: False
# isArray: false
@export var downloadUrl: String = "":
	set(value):
		__downloadUrl__was__set = true
		downloadUrl = value
var __downloadUrl__was__set := false

# Required: False
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__active__was__set:
		bzz_dictionary["active"] = self.active
	if self.__valid__was__set:
		bzz_dictionary["valid"] = self.valid
	if self.__device__was__set:
		bzz_dictionary["device"] = self.device
	if self.__minimum__was__set:
		bzz_dictionary["minimum"] = self.minimum
	if self.__maximum__was__set:
		bzz_dictionary["maximum"] = self.maximum
	if self.__downloadUrl__was__set:
		bzz_dictionary["downloadUrl"] = self.downloadUrl
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("active"):
		me.active = from_dict["active"]
	if from_dict.has("valid"):
		me.valid = from_dict["valid"]
	if from_dict.has("device"):
		me.device = AudienceDevice.bzz_denormalize_single(from_dict["device"])
	if from_dict.has("minimum"):
		me.minimum = from_dict["minimum"]
	if from_dict.has("maximum"):
		me.maximum = from_dict["maximum"]
	if from_dict.has("downloadUrl"):
		me.downloadUrl = from_dict["downloadUrl"]
	if from_dict.has("description"):
		me.description = from_dict["description"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

