/*
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OrsonAiTechTuneResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T18:59:03.014614210Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class OrsonAiTechTuneResponse {
  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @javax.annotation.Nullable
  private String requestId;

  public static final String SERIALIZED_NAME_RESPONSE_CODE = "responseCode";
  @SerializedName(SERIALIZED_NAME_RESPONSE_CODE)
  @javax.annotation.Nullable
  private Integer responseCode;

  public static final String SERIALIZED_NAME_RESPONSE_RAW = "responseRaw";
  @SerializedName(SERIALIZED_NAME_RESPONSE_RAW)
  @javax.annotation.Nullable
  private String responseRaw;

  public static final String SERIALIZED_NAME_PEOPLE = "people";
  @SerializedName(SERIALIZED_NAME_PEOPLE)
  @javax.annotation.Nullable
  private Integer people;

  public static final String SERIALIZED_NAME_WAS_CUTOFF = "wasCutoff";
  @SerializedName(SERIALIZED_NAME_WAS_CUTOFF)
  @javax.annotation.Nullable
  private Boolean wasCutoff;

  public static final String SERIALIZED_NAME_FRAMES = "frames";
  @SerializedName(SERIALIZED_NAME_FRAMES)
  @javax.annotation.Nullable
  private Integer frames;

  public static final String SERIALIZED_NAME_FRAMES_WITHOUT_A_FACE = "framesWithoutAFace";
  @SerializedName(SERIALIZED_NAME_FRAMES_WITHOUT_A_FACE)
  @javax.annotation.Nullable
  private Integer framesWithoutAFace;

  public static final String SERIALIZED_NAME_FRAMES_WITH_FACE_OFFSCREEN = "framesWithFaceOffscreen";
  @SerializedName(SERIALIZED_NAME_FRAMES_WITH_FACE_OFFSCREEN)
  @javax.annotation.Nullable
  private Integer framesWithFaceOffscreen;

  public static final String SERIALIZED_NAME_FRAMES_WITH_WRONG_NUMBER_OF_PEOPLE = "framesWithWrongNumberOfPeople";
  @SerializedName(SERIALIZED_NAME_FRAMES_WITH_WRONG_NUMBER_OF_PEOPLE)
  @javax.annotation.Nullable
  private Integer framesWithWrongNumberOfPeople;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  @javax.annotation.Nullable
  private Integer height;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  @javax.annotation.Nullable
  private Integer width;

  public static final String SERIALIZED_NAME_FPS = "fps";
  @SerializedName(SERIALIZED_NAME_FPS)
  @javax.annotation.Nullable
  private Integer fps;

  public OrsonAiTechTuneResponse() {
  }

  public OrsonAiTechTuneResponse requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  public OrsonAiTechTuneResponse responseCode(@javax.annotation.Nullable Integer responseCode) {
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Get responseCode
   * @return responseCode
   */
  @javax.annotation.Nullable
  public Integer getResponseCode() {
    return responseCode;
  }

  public void setResponseCode(@javax.annotation.Nullable Integer responseCode) {
    this.responseCode = responseCode;
  }


  public OrsonAiTechTuneResponse responseRaw(@javax.annotation.Nullable String responseRaw) {
    this.responseRaw = responseRaw;
    return this;
  }

  /**
   * Get responseRaw
   * @return responseRaw
   */
  @javax.annotation.Nullable
  public String getResponseRaw() {
    return responseRaw;
  }

  public void setResponseRaw(@javax.annotation.Nullable String responseRaw) {
    this.responseRaw = responseRaw;
  }


  public OrsonAiTechTuneResponse people(@javax.annotation.Nullable Integer people) {
    this.people = people;
    return this;
  }

  /**
   * Get people
   * @return people
   */
  @javax.annotation.Nullable
  public Integer getPeople() {
    return people;
  }

  public void setPeople(@javax.annotation.Nullable Integer people) {
    this.people = people;
  }


  public OrsonAiTechTuneResponse wasCutoff(@javax.annotation.Nullable Boolean wasCutoff) {
    this.wasCutoff = wasCutoff;
    return this;
  }

  /**
   * Get wasCutoff
   * @return wasCutoff
   */
  @javax.annotation.Nullable
  public Boolean getWasCutoff() {
    return wasCutoff;
  }

  public void setWasCutoff(@javax.annotation.Nullable Boolean wasCutoff) {
    this.wasCutoff = wasCutoff;
  }


  public OrsonAiTechTuneResponse frames(@javax.annotation.Nullable Integer frames) {
    this.frames = frames;
    return this;
  }

  /**
   * Get frames
   * @return frames
   */
  @javax.annotation.Nullable
  public Integer getFrames() {
    return frames;
  }

  public void setFrames(@javax.annotation.Nullable Integer frames) {
    this.frames = frames;
  }


  public OrsonAiTechTuneResponse framesWithoutAFace(@javax.annotation.Nullable Integer framesWithoutAFace) {
    this.framesWithoutAFace = framesWithoutAFace;
    return this;
  }

  /**
   * Get framesWithoutAFace
   * @return framesWithoutAFace
   */
  @javax.annotation.Nullable
  public Integer getFramesWithoutAFace() {
    return framesWithoutAFace;
  }

  public void setFramesWithoutAFace(@javax.annotation.Nullable Integer framesWithoutAFace) {
    this.framesWithoutAFace = framesWithoutAFace;
  }


  public OrsonAiTechTuneResponse framesWithFaceOffscreen(@javax.annotation.Nullable Integer framesWithFaceOffscreen) {
    this.framesWithFaceOffscreen = framesWithFaceOffscreen;
    return this;
  }

  /**
   * Get framesWithFaceOffscreen
   * @return framesWithFaceOffscreen
   */
  @javax.annotation.Nullable
  public Integer getFramesWithFaceOffscreen() {
    return framesWithFaceOffscreen;
  }

  public void setFramesWithFaceOffscreen(@javax.annotation.Nullable Integer framesWithFaceOffscreen) {
    this.framesWithFaceOffscreen = framesWithFaceOffscreen;
  }


  public OrsonAiTechTuneResponse framesWithWrongNumberOfPeople(@javax.annotation.Nullable Integer framesWithWrongNumberOfPeople) {
    this.framesWithWrongNumberOfPeople = framesWithWrongNumberOfPeople;
    return this;
  }

  /**
   * Get framesWithWrongNumberOfPeople
   * @return framesWithWrongNumberOfPeople
   */
  @javax.annotation.Nullable
  public Integer getFramesWithWrongNumberOfPeople() {
    return framesWithWrongNumberOfPeople;
  }

  public void setFramesWithWrongNumberOfPeople(@javax.annotation.Nullable Integer framesWithWrongNumberOfPeople) {
    this.framesWithWrongNumberOfPeople = framesWithWrongNumberOfPeople;
  }


  public OrsonAiTechTuneResponse height(@javax.annotation.Nullable Integer height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   */
  @javax.annotation.Nullable
  public Integer getHeight() {
    return height;
  }

  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }


  public OrsonAiTechTuneResponse width(@javax.annotation.Nullable Integer width) {
    this.width = width;
    return this;
  }

  /**
   * Get width
   * @return width
   */
  @javax.annotation.Nullable
  public Integer getWidth() {
    return width;
  }

  public void setWidth(@javax.annotation.Nullable Integer width) {
    this.width = width;
  }


  public OrsonAiTechTuneResponse fps(@javax.annotation.Nullable Integer fps) {
    this.fps = fps;
    return this;
  }

  /**
   * Get fps
   * @return fps
   */
  @javax.annotation.Nullable
  public Integer getFps() {
    return fps;
  }

  public void setFps(@javax.annotation.Nullable Integer fps) {
    this.fps = fps;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrsonAiTechTuneResponse orsonAiTechTuneResponse = (OrsonAiTechTuneResponse) o;
    return Objects.equals(this.requestId, orsonAiTechTuneResponse.requestId) &&
        Objects.equals(this.responseCode, orsonAiTechTuneResponse.responseCode) &&
        Objects.equals(this.responseRaw, orsonAiTechTuneResponse.responseRaw) &&
        Objects.equals(this.people, orsonAiTechTuneResponse.people) &&
        Objects.equals(this.wasCutoff, orsonAiTechTuneResponse.wasCutoff) &&
        Objects.equals(this.frames, orsonAiTechTuneResponse.frames) &&
        Objects.equals(this.framesWithoutAFace, orsonAiTechTuneResponse.framesWithoutAFace) &&
        Objects.equals(this.framesWithFaceOffscreen, orsonAiTechTuneResponse.framesWithFaceOffscreen) &&
        Objects.equals(this.framesWithWrongNumberOfPeople, orsonAiTechTuneResponse.framesWithWrongNumberOfPeople) &&
        Objects.equals(this.height, orsonAiTechTuneResponse.height) &&
        Objects.equals(this.width, orsonAiTechTuneResponse.width) &&
        Objects.equals(this.fps, orsonAiTechTuneResponse.fps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, responseCode, responseRaw, people, wasCutoff, frames, framesWithoutAFace, framesWithFaceOffscreen, framesWithWrongNumberOfPeople, height, width, fps);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrsonAiTechTuneResponse {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseRaw: ").append(toIndentedString(responseRaw)).append("\n");
    sb.append("    people: ").append(toIndentedString(people)).append("\n");
    sb.append("    wasCutoff: ").append(toIndentedString(wasCutoff)).append("\n");
    sb.append("    frames: ").append(toIndentedString(frames)).append("\n");
    sb.append("    framesWithoutAFace: ").append(toIndentedString(framesWithoutAFace)).append("\n");
    sb.append("    framesWithFaceOffscreen: ").append(toIndentedString(framesWithFaceOffscreen)).append("\n");
    sb.append("    framesWithWrongNumberOfPeople: ").append(toIndentedString(framesWithWrongNumberOfPeople)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    fps: ").append(toIndentedString(fps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("requestId", "responseCode", "responseRaw", "people", "wasCutoff", "frames", "framesWithoutAFace", "framesWithFaceOffscreen", "framesWithWrongNumberOfPeople", "height", "width", "fps"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrsonAiTechTuneResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrsonAiTechTuneResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in OrsonAiTechTuneResponse is not found in the empty JSON string", OrsonAiTechTuneResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrsonAiTechTuneResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OrsonAiTechTuneResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("requestId") != null && !jsonObj.get("requestId").isJsonNull()) && !jsonObj.get("requestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `requestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestId").toString()));
      }
      if ((jsonObj.get("responseRaw") != null && !jsonObj.get("responseRaw").isJsonNull()) && !jsonObj.get("responseRaw").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `responseRaw` to be a primitive type in the JSON string but got `%s`", jsonObj.get("responseRaw").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrsonAiTechTuneResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrsonAiTechTuneResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrsonAiTechTuneResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrsonAiTechTuneResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OrsonAiTechTuneResponse>() {
           @Override
           public void write(JsonWriter out, OrsonAiTechTuneResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrsonAiTechTuneResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrsonAiTechTuneResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrsonAiTechTuneResponse
   * @throws IOException if the JSON string is invalid with respect to OrsonAiTechTuneResponse
   */
  public static OrsonAiTechTuneResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrsonAiTechTuneResponse.class);
  }

  /**
   * Convert an instance of OrsonAiTechTuneResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

