// <auto-generated>
/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ShipmentBatch
    /// </summary>
    public partial class ShipmentBatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipmentBatch" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="created">created</param>
        /// <param name="updated">updated</param>
        /// <param name="active">active</param>
        /// <param name="valid">valid</param>
        /// <param name="retailer">retailer</param>
        /// <param name="hub">hub</param>
        /// <param name="program">program</param>
        /// <param name="shipmentImportStatuses">shipmentImportStatuses</param>
        /// <param name="shipments">shipments</param>
        /// <param name="uploaded">uploaded</param>
        /// <param name="started">started</param>
        /// <param name="optimizationStarted">optimizationStarted</param>
        /// <param name="completed">completed</param>
        /// <param name="optimizationCompleted">optimizationCompleted</param>
        /// <param name="source">source</param>
        /// <param name="externalId">externalId</param>
        /// <param name="total">total</param>
        /// <param name="processedCount">processedCount</param>
        /// <param name="successCount">successCount</param>
        /// <param name="failedCount">failedCount</param>
        /// <param name="validCount">validCount</param>
        /// <param name="invalidCount">invalidCount</param>
        /// <param name="averageTravelSpeed">averageTravelSpeed</param>
        /// <param name="maxSeconds">maxSeconds</param>
        /// <param name="importStatus">importStatus</param>
        /// <param name="totalRoutes">totalRoutes</param>
        /// <param name="routesCreated">routesCreated</param>
        /// <param name="totalLegsRequests">totalLegsRequests</param>
        /// <param name="legsRequested">legsRequested</param>
        /// <param name="initScore">initScore</param>
        /// <param name="hardScore">hardScore</param>
        /// <param name="mediumScore">mediumScore</param>
        /// <param name="softScore">softScore</param>
        [JsonConstructor]
        public ShipmentBatch(Option<long?> id = default, Option<DateTime?> created = default, Option<DateTime?> updated = default, Option<bool?> active = default, Option<bool?> valid = default, Option<Retailer?> retailer = default, Option<ServiceHub?> hub = default, Option<Program?> program = default, Option<List<ShipmentImportStatus>?> shipmentImportStatuses = default, Option<List<Shipment>?> shipments = default, Option<DateTime?> uploaded = default, Option<DateTime?> started = default, Option<DateTime?> optimizationStarted = default, Option<DateTime?> completed = default, Option<DateTime?> optimizationCompleted = default, Option<string?> source = default, Option<string?> externalId = default, Option<int?> total = default, Option<int?> processedCount = default, Option<int?> successCount = default, Option<int?> failedCount = default, Option<int?> validCount = default, Option<int?> invalidCount = default, Option<double?> averageTravelSpeed = default, Option<long?> maxSeconds = default, Option<ImportStatusEnum?> importStatus = default, Option<int?> totalRoutes = default, Option<int?> routesCreated = default, Option<int?> totalLegsRequests = default, Option<int?> legsRequested = default, Option<int?> initScore = default, Option<long?> hardScore = default, Option<long?> mediumScore = default, Option<long?> softScore = default)
        {
            IdOption = id;
            CreatedOption = created;
            UpdatedOption = updated;
            ActiveOption = active;
            ValidOption = valid;
            RetailerOption = retailer;
            HubOption = hub;
            ProgramOption = program;
            ShipmentImportStatusesOption = shipmentImportStatuses;
            ShipmentsOption = shipments;
            UploadedOption = uploaded;
            StartedOption = started;
            OptimizationStartedOption = optimizationStarted;
            CompletedOption = completed;
            OptimizationCompletedOption = optimizationCompleted;
            SourceOption = source;
            ExternalIdOption = externalId;
            TotalOption = total;
            ProcessedCountOption = processedCount;
            SuccessCountOption = successCount;
            FailedCountOption = failedCount;
            ValidCountOption = validCount;
            InvalidCountOption = invalidCount;
            AverageTravelSpeedOption = averageTravelSpeed;
            MaxSecondsOption = maxSeconds;
            ImportStatusOption = importStatus;
            TotalRoutesOption = totalRoutes;
            RoutesCreatedOption = routesCreated;
            TotalLegsRequestsOption = totalLegsRequests;
            LegsRequestedOption = legsRequested;
            InitScoreOption = initScore;
            HardScoreOption = hardScore;
            MediumScoreOption = mediumScore;
            SoftScoreOption = softScore;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines ImportStatus
        /// </summary>
        public enum ImportStatusEnum
        {
            /// <summary>
            /// Enum NEW for value: NEW
            /// </summary>
            NEW = 1,

            /// <summary>
            /// Enum STARTED for value: STARTED
            /// </summary>
            STARTED = 2,

            /// <summary>
            /// Enum FETCHINGDISTANCEDATA for value: FETCHING_DISTANCE_DATA
            /// </summary>
            FETCHINGDISTANCEDATA = 3,

            /// <summary>
            /// Enum OPTIMIZING for value: OPTIMIZING
            /// </summary>
            OPTIMIZING = 4,

            /// <summary>
            /// Enum CREATINGROUTES for value: CREATING_ROUTES
            /// </summary>
            CREATINGROUTES = 5,

            /// <summary>
            /// Enum COMPLETED for value: COMPLETED
            /// </summary>
            COMPLETED = 6,

            /// <summary>
            /// Enum INCOMPLETE for value: INCOMPLETE
            /// </summary>
            INCOMPLETE = 7
        }

        /// <summary>
        /// Returns a <see cref="ImportStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ImportStatusEnum ImportStatusEnumFromString(string value)
        {
            if (value.Equals("NEW"))
                return ImportStatusEnum.NEW;

            if (value.Equals("STARTED"))
                return ImportStatusEnum.STARTED;

            if (value.Equals("FETCHING_DISTANCE_DATA"))
                return ImportStatusEnum.FETCHINGDISTANCEDATA;

            if (value.Equals("OPTIMIZING"))
                return ImportStatusEnum.OPTIMIZING;

            if (value.Equals("CREATING_ROUTES"))
                return ImportStatusEnum.CREATINGROUTES;

            if (value.Equals("COMPLETED"))
                return ImportStatusEnum.COMPLETED;

            if (value.Equals("INCOMPLETE"))
                return ImportStatusEnum.INCOMPLETE;

            throw new NotImplementedException($"Could not convert value to type ImportStatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ImportStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ImportStatusEnum? ImportStatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("NEW"))
                return ImportStatusEnum.NEW;

            if (value.Equals("STARTED"))
                return ImportStatusEnum.STARTED;

            if (value.Equals("FETCHING_DISTANCE_DATA"))
                return ImportStatusEnum.FETCHINGDISTANCEDATA;

            if (value.Equals("OPTIMIZING"))
                return ImportStatusEnum.OPTIMIZING;

            if (value.Equals("CREATING_ROUTES"))
                return ImportStatusEnum.CREATINGROUTES;

            if (value.Equals("COMPLETED"))
                return ImportStatusEnum.COMPLETED;

            if (value.Equals("INCOMPLETE"))
                return ImportStatusEnum.INCOMPLETE;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ImportStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ImportStatusEnumToJsonValue(ImportStatusEnum? value)
        {
            if (value == ImportStatusEnum.NEW)
                return "NEW";

            if (value == ImportStatusEnum.STARTED)
                return "STARTED";

            if (value == ImportStatusEnum.FETCHINGDISTANCEDATA)
                return "FETCHING_DISTANCE_DATA";

            if (value == ImportStatusEnum.OPTIMIZING)
                return "OPTIMIZING";

            if (value == ImportStatusEnum.CREATINGROUTES)
                return "CREATING_ROUTES";

            if (value == ImportStatusEnum.COMPLETED)
                return "COMPLETED";

            if (value == ImportStatusEnum.INCOMPLETE)
                return "INCOMPLETE";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ImportStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ImportStatusEnum?> ImportStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImportStatus
        /// </summary>
        [JsonPropertyName("importStatus")]
        public ImportStatusEnum? ImportStatus { get { return this.ImportStatusOption; } set { this.ImportStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Created
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public DateTime? Created { get { return this.CreatedOption; } set { this.CreatedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Updated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Updated
        /// </summary>
        [JsonPropertyName("updated")]
        public DateTime? Updated { get { return this.UpdatedOption; } set { this.UpdatedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } set { this.ActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of Valid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ValidOption { get; private set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("valid")]
        public bool? Valid { get { return this.ValidOption; } set { this.ValidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Retailer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Retailer?> RetailerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Retailer
        /// </summary>
        [JsonPropertyName("retailer")]
        public Retailer? Retailer { get { return this.RetailerOption; } set { this.RetailerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hub
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ServiceHub?> HubOption { get; private set; }

        /// <summary>
        /// Gets or Sets Hub
        /// </summary>
        [JsonPropertyName("hub")]
        public ServiceHub? Hub { get { return this.HubOption; } set { this.HubOption = new(value); } }

        /// <summary>
        /// Used to track the state of Program
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Program?> ProgramOption { get; private set; }

        /// <summary>
        /// Gets or Sets Program
        /// </summary>
        [JsonPropertyName("program")]
        public Program? Program { get { return this.ProgramOption; } set { this.ProgramOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShipmentImportStatuses
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ShipmentImportStatus>?> ShipmentImportStatusesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShipmentImportStatuses
        /// </summary>
        [JsonPropertyName("shipmentImportStatuses")]
        public List<ShipmentImportStatus>? ShipmentImportStatuses { get { return this.ShipmentImportStatusesOption; } set { this.ShipmentImportStatusesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Shipments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Shipment>?> ShipmentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Shipments
        /// </summary>
        [JsonPropertyName("shipments")]
        public List<Shipment>? Shipments { get { return this.ShipmentsOption; } set { this.ShipmentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Uploaded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UploadedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Uploaded
        /// </summary>
        [JsonPropertyName("uploaded")]
        public DateTime? Uploaded { get { return this.UploadedOption; } set { this.UploadedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Started
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Started
        /// </summary>
        [JsonPropertyName("started")]
        public DateTime? Started { get { return this.StartedOption; } set { this.StartedOption = new(value); } }

        /// <summary>
        /// Used to track the state of OptimizationStarted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> OptimizationStartedOption { get; private set; }

        /// <summary>
        /// Gets or Sets OptimizationStarted
        /// </summary>
        [JsonPropertyName("optimizationStarted")]
        public DateTime? OptimizationStarted { get { return this.OptimizationStartedOption; } set { this.OptimizationStartedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Completed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Completed
        /// </summary>
        [JsonPropertyName("completed")]
        public DateTime? Completed { get { return this.CompletedOption; } set { this.CompletedOption = new(value); } }

        /// <summary>
        /// Used to track the state of OptimizationCompleted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> OptimizationCompletedOption { get; private set; }

        /// <summary>
        /// Gets or Sets OptimizationCompleted
        /// </summary>
        [JsonPropertyName("optimizationCompleted")]
        public DateTime? OptimizationCompleted { get { return this.OptimizationCompletedOption; } set { this.OptimizationCompletedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string? Source { get { return this.SourceOption; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Total
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalOption { get; private set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int? Total { get { return this.TotalOption; } set { this.TotalOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProcessedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProcessedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProcessedCount
        /// </summary>
        [JsonPropertyName("processedCount")]
        public int? ProcessedCount { get { return this.ProcessedCountOption; } set { this.ProcessedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuccessCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuccessCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuccessCount
        /// </summary>
        [JsonPropertyName("successCount")]
        public int? SuccessCount { get { return this.SuccessCountOption; } set { this.SuccessCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailedCount
        /// </summary>
        [JsonPropertyName("failedCount")]
        public int? FailedCount { get { return this.FailedCountOption; } set { this.FailedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValidCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ValidCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValidCount
        /// </summary>
        [JsonPropertyName("validCount")]
        public int? ValidCount { get { return this.ValidCountOption; } set { this.ValidCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of InvalidCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> InvalidCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvalidCount
        /// </summary>
        [JsonPropertyName("invalidCount")]
        public int? InvalidCount { get { return this.InvalidCountOption; } set { this.InvalidCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of AverageTravelSpeed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AverageTravelSpeedOption { get; private set; }

        /// <summary>
        /// Gets or Sets AverageTravelSpeed
        /// </summary>
        [JsonPropertyName("averageTravelSpeed")]
        public double? AverageTravelSpeed { get { return this.AverageTravelSpeedOption; } set { this.AverageTravelSpeedOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaxSeconds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> MaxSecondsOption { get; private set; }

        /// <summary>
        /// Gets or Sets MaxSeconds
        /// </summary>
        [JsonPropertyName("maxSeconds")]
        public long? MaxSeconds { get { return this.MaxSecondsOption; } set { this.MaxSecondsOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalRoutes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalRoutesOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalRoutes
        /// </summary>
        [JsonPropertyName("totalRoutes")]
        public int? TotalRoutes { get { return this.TotalRoutesOption; } set { this.TotalRoutesOption = new(value); } }

        /// <summary>
        /// Used to track the state of RoutesCreated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RoutesCreatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets RoutesCreated
        /// </summary>
        [JsonPropertyName("routesCreated")]
        public int? RoutesCreated { get { return this.RoutesCreatedOption; } set { this.RoutesCreatedOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalLegsRequests
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalLegsRequestsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalLegsRequests
        /// </summary>
        [JsonPropertyName("totalLegsRequests")]
        public int? TotalLegsRequests { get { return this.TotalLegsRequestsOption; } set { this.TotalLegsRequestsOption = new(value); } }

        /// <summary>
        /// Used to track the state of LegsRequested
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LegsRequestedOption { get; private set; }

        /// <summary>
        /// Gets or Sets LegsRequested
        /// </summary>
        [JsonPropertyName("legsRequested")]
        public int? LegsRequested { get { return this.LegsRequestedOption; } set { this.LegsRequestedOption = new(value); } }

        /// <summary>
        /// Used to track the state of InitScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> InitScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets InitScore
        /// </summary>
        [JsonPropertyName("initScore")]
        public int? InitScore { get { return this.InitScoreOption; } set { this.InitScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of HardScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> HardScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets HardScore
        /// </summary>
        [JsonPropertyName("hardScore")]
        public long? HardScore { get { return this.HardScoreOption; } set { this.HardScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of MediumScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> MediumScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets MediumScore
        /// </summary>
        [JsonPropertyName("mediumScore")]
        public long? MediumScore { get { return this.MediumScoreOption; } set { this.MediumScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of SoftScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SoftScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets SoftScore
        /// </summary>
        [JsonPropertyName("softScore")]
        public long? SoftScore { get { return this.SoftScoreOption; } set { this.SoftScoreOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipmentBatch {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Retailer: ").Append(Retailer).Append("\n");
            sb.Append("  Hub: ").Append(Hub).Append("\n");
            sb.Append("  Program: ").Append(Program).Append("\n");
            sb.Append("  ShipmentImportStatuses: ").Append(ShipmentImportStatuses).Append("\n");
            sb.Append("  Shipments: ").Append(Shipments).Append("\n");
            sb.Append("  Uploaded: ").Append(Uploaded).Append("\n");
            sb.Append("  Started: ").Append(Started).Append("\n");
            sb.Append("  OptimizationStarted: ").Append(OptimizationStarted).Append("\n");
            sb.Append("  Completed: ").Append(Completed).Append("\n");
            sb.Append("  OptimizationCompleted: ").Append(OptimizationCompleted).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  ProcessedCount: ").Append(ProcessedCount).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("  FailedCount: ").Append(FailedCount).Append("\n");
            sb.Append("  ValidCount: ").Append(ValidCount).Append("\n");
            sb.Append("  InvalidCount: ").Append(InvalidCount).Append("\n");
            sb.Append("  AverageTravelSpeed: ").Append(AverageTravelSpeed).Append("\n");
            sb.Append("  MaxSeconds: ").Append(MaxSeconds).Append("\n");
            sb.Append("  ImportStatus: ").Append(ImportStatus).Append("\n");
            sb.Append("  TotalRoutes: ").Append(TotalRoutes).Append("\n");
            sb.Append("  RoutesCreated: ").Append(RoutesCreated).Append("\n");
            sb.Append("  TotalLegsRequests: ").Append(TotalLegsRequests).Append("\n");
            sb.Append("  LegsRequested: ").Append(LegsRequested).Append("\n");
            sb.Append("  InitScore: ").Append(InitScore).Append("\n");
            sb.Append("  HardScore: ").Append(HardScore).Append("\n");
            sb.Append("  MediumScore: ").Append(MediumScore).Append("\n");
            sb.Append("  SoftScore: ").Append(SoftScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ShipmentBatch" />
    /// </summary>
    public class ShipmentBatchJsonConverter : JsonConverter<ShipmentBatch>
    {
        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public static string CreatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Updated
        /// </summary>
        public static string UpdatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Uploaded
        /// </summary>
        public static string UploadedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Started
        /// </summary>
        public static string StartedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize OptimizationStarted
        /// </summary>
        public static string OptimizationStartedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Completed
        /// </summary>
        public static string CompletedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize OptimizationCompleted
        /// </summary>
        public static string OptimizationCompletedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ShipmentBatch" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ShipmentBatch Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<DateTime?> created = default;
            Option<DateTime?> updated = default;
            Option<bool?> active = default;
            Option<bool?> valid = default;
            Option<Retailer?> retailer = default;
            Option<ServiceHub?> hub = default;
            Option<Program?> program = default;
            Option<List<ShipmentImportStatus>?> shipmentImportStatuses = default;
            Option<List<Shipment>?> shipments = default;
            Option<DateTime?> uploaded = default;
            Option<DateTime?> started = default;
            Option<DateTime?> optimizationStarted = default;
            Option<DateTime?> completed = default;
            Option<DateTime?> optimizationCompleted = default;
            Option<string?> source = default;
            Option<string?> externalId = default;
            Option<int?> total = default;
            Option<int?> processedCount = default;
            Option<int?> successCount = default;
            Option<int?> failedCount = default;
            Option<int?> validCount = default;
            Option<int?> invalidCount = default;
            Option<double?> averageTravelSpeed = default;
            Option<long?> maxSeconds = default;
            Option<ShipmentBatch.ImportStatusEnum?> importStatus = default;
            Option<int?> totalRoutes = default;
            Option<int?> routesCreated = default;
            Option<int?> totalLegsRequests = default;
            Option<int?> legsRequested = default;
            Option<int?> initScore = default;
            Option<long?> hardScore = default;
            Option<long?> mediumScore = default;
            Option<long?> softScore = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "created":
                            created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated":
                            updated = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "active":
                            active = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "retailer":
                            retailer = new Option<Retailer?>(JsonSerializer.Deserialize<Retailer>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hub":
                            hub = new Option<ServiceHub?>(JsonSerializer.Deserialize<ServiceHub>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "program":
                            program = new Option<Program?>(JsonSerializer.Deserialize<Program>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "shipmentImportStatuses":
                            shipmentImportStatuses = new Option<List<ShipmentImportStatus>?>(JsonSerializer.Deserialize<List<ShipmentImportStatus>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "shipments":
                            shipments = new Option<List<Shipment>?>(JsonSerializer.Deserialize<List<Shipment>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "uploaded":
                            uploaded = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "started":
                            started = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "optimizationStarted":
                            optimizationStarted = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completed":
                            completed = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "optimizationCompleted":
                            optimizationCompleted = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "processedCount":
                            processedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "successCount":
                            successCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failedCount":
                            failedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "validCount":
                            validCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "invalidCount":
                            invalidCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "averageTravelSpeed":
                            averageTravelSpeed = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "maxSeconds":
                            maxSeconds = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "importStatus":
                            string? importStatusRawValue = utf8JsonReader.GetString();
                            if (importStatusRawValue != null)
                                importStatus = new Option<ShipmentBatch.ImportStatusEnum?>(ShipmentBatch.ImportStatusEnumFromStringOrDefault(importStatusRawValue));
                            break;
                        case "totalRoutes":
                            totalRoutes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "routesCreated":
                            routesCreated = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "totalLegsRequests":
                            totalLegsRequests = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "legsRequested":
                            legsRequested = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "initScore":
                            initScore = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "hardScore":
                            hardScore = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "mediumScore":
                            mediumScore = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "softScore":
                            softScore = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ShipmentBatch.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class ShipmentBatch.");

            if (updated.IsSet && updated.Value == null)
                throw new ArgumentNullException(nameof(updated), "Property is not nullable for class ShipmentBatch.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class ShipmentBatch.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class ShipmentBatch.");

            if (retailer.IsSet && retailer.Value == null)
                throw new ArgumentNullException(nameof(retailer), "Property is not nullable for class ShipmentBatch.");

            if (hub.IsSet && hub.Value == null)
                throw new ArgumentNullException(nameof(hub), "Property is not nullable for class ShipmentBatch.");

            if (program.IsSet && program.Value == null)
                throw new ArgumentNullException(nameof(program), "Property is not nullable for class ShipmentBatch.");

            if (shipmentImportStatuses.IsSet && shipmentImportStatuses.Value == null)
                throw new ArgumentNullException(nameof(shipmentImportStatuses), "Property is not nullable for class ShipmentBatch.");

            if (shipments.IsSet && shipments.Value == null)
                throw new ArgumentNullException(nameof(shipments), "Property is not nullable for class ShipmentBatch.");

            if (uploaded.IsSet && uploaded.Value == null)
                throw new ArgumentNullException(nameof(uploaded), "Property is not nullable for class ShipmentBatch.");

            if (started.IsSet && started.Value == null)
                throw new ArgumentNullException(nameof(started), "Property is not nullable for class ShipmentBatch.");

            if (optimizationStarted.IsSet && optimizationStarted.Value == null)
                throw new ArgumentNullException(nameof(optimizationStarted), "Property is not nullable for class ShipmentBatch.");

            if (completed.IsSet && completed.Value == null)
                throw new ArgumentNullException(nameof(completed), "Property is not nullable for class ShipmentBatch.");

            if (optimizationCompleted.IsSet && optimizationCompleted.Value == null)
                throw new ArgumentNullException(nameof(optimizationCompleted), "Property is not nullable for class ShipmentBatch.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class ShipmentBatch.");

            if (externalId.IsSet && externalId.Value == null)
                throw new ArgumentNullException(nameof(externalId), "Property is not nullable for class ShipmentBatch.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class ShipmentBatch.");

            if (processedCount.IsSet && processedCount.Value == null)
                throw new ArgumentNullException(nameof(processedCount), "Property is not nullable for class ShipmentBatch.");

            if (successCount.IsSet && successCount.Value == null)
                throw new ArgumentNullException(nameof(successCount), "Property is not nullable for class ShipmentBatch.");

            if (failedCount.IsSet && failedCount.Value == null)
                throw new ArgumentNullException(nameof(failedCount), "Property is not nullable for class ShipmentBatch.");

            if (validCount.IsSet && validCount.Value == null)
                throw new ArgumentNullException(nameof(validCount), "Property is not nullable for class ShipmentBatch.");

            if (invalidCount.IsSet && invalidCount.Value == null)
                throw new ArgumentNullException(nameof(invalidCount), "Property is not nullable for class ShipmentBatch.");

            if (averageTravelSpeed.IsSet && averageTravelSpeed.Value == null)
                throw new ArgumentNullException(nameof(averageTravelSpeed), "Property is not nullable for class ShipmentBatch.");

            if (maxSeconds.IsSet && maxSeconds.Value == null)
                throw new ArgumentNullException(nameof(maxSeconds), "Property is not nullable for class ShipmentBatch.");

            if (importStatus.IsSet && importStatus.Value == null)
                throw new ArgumentNullException(nameof(importStatus), "Property is not nullable for class ShipmentBatch.");

            if (totalRoutes.IsSet && totalRoutes.Value == null)
                throw new ArgumentNullException(nameof(totalRoutes), "Property is not nullable for class ShipmentBatch.");

            if (routesCreated.IsSet && routesCreated.Value == null)
                throw new ArgumentNullException(nameof(routesCreated), "Property is not nullable for class ShipmentBatch.");

            if (totalLegsRequests.IsSet && totalLegsRequests.Value == null)
                throw new ArgumentNullException(nameof(totalLegsRequests), "Property is not nullable for class ShipmentBatch.");

            if (legsRequested.IsSet && legsRequested.Value == null)
                throw new ArgumentNullException(nameof(legsRequested), "Property is not nullable for class ShipmentBatch.");

            if (initScore.IsSet && initScore.Value == null)
                throw new ArgumentNullException(nameof(initScore), "Property is not nullable for class ShipmentBatch.");

            if (hardScore.IsSet && hardScore.Value == null)
                throw new ArgumentNullException(nameof(hardScore), "Property is not nullable for class ShipmentBatch.");

            if (mediumScore.IsSet && mediumScore.Value == null)
                throw new ArgumentNullException(nameof(mediumScore), "Property is not nullable for class ShipmentBatch.");

            if (softScore.IsSet && softScore.Value == null)
                throw new ArgumentNullException(nameof(softScore), "Property is not nullable for class ShipmentBatch.");

            return new ShipmentBatch(id, created, updated, active, valid, retailer, hub, program, shipmentImportStatuses, shipments, uploaded, started, optimizationStarted, completed, optimizationCompleted, source, externalId, total, processedCount, successCount, failedCount, validCount, invalidCount, averageTravelSpeed, maxSeconds, importStatus, totalRoutes, routesCreated, totalLegsRequests, legsRequested, initScore, hardScore, mediumScore, softScore);
        }

        /// <summary>
        /// Serializes a <see cref="ShipmentBatch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shipmentBatch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ShipmentBatch shipmentBatch, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, shipmentBatch, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ShipmentBatch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shipmentBatch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ShipmentBatch shipmentBatch, JsonSerializerOptions jsonSerializerOptions)
        {
            if (shipmentBatch.RetailerOption.IsSet && shipmentBatch.Retailer == null)
                throw new ArgumentNullException(nameof(shipmentBatch.Retailer), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.HubOption.IsSet && shipmentBatch.Hub == null)
                throw new ArgumentNullException(nameof(shipmentBatch.Hub), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.ProgramOption.IsSet && shipmentBatch.Program == null)
                throw new ArgumentNullException(nameof(shipmentBatch.Program), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.ShipmentImportStatusesOption.IsSet && shipmentBatch.ShipmentImportStatuses == null)
                throw new ArgumentNullException(nameof(shipmentBatch.ShipmentImportStatuses), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.ShipmentsOption.IsSet && shipmentBatch.Shipments == null)
                throw new ArgumentNullException(nameof(shipmentBatch.Shipments), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.SourceOption.IsSet && shipmentBatch.Source == null)
                throw new ArgumentNullException(nameof(shipmentBatch.Source), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.ExternalIdOption.IsSet && shipmentBatch.ExternalId == null)
                throw new ArgumentNullException(nameof(shipmentBatch.ExternalId), "Property is required for class ShipmentBatch.");

            if (shipmentBatch.IdOption.IsSet)
                writer.WriteNumber("id", shipmentBatch.IdOption.Value!.Value);

            if (shipmentBatch.CreatedOption.IsSet)
                writer.WriteString("created", shipmentBatch.CreatedOption.Value!.Value.ToString(CreatedFormat));

            if (shipmentBatch.UpdatedOption.IsSet)
                writer.WriteString("updated", shipmentBatch.UpdatedOption.Value!.Value.ToString(UpdatedFormat));

            if (shipmentBatch.ActiveOption.IsSet)
                writer.WriteBoolean("active", shipmentBatch.ActiveOption.Value!.Value);

            if (shipmentBatch.ValidOption.IsSet)
                writer.WriteBoolean("valid", shipmentBatch.ValidOption.Value!.Value);

            if (shipmentBatch.RetailerOption.IsSet)
            {
                writer.WritePropertyName("retailer");
                JsonSerializer.Serialize(writer, shipmentBatch.Retailer, jsonSerializerOptions);
            }
            if (shipmentBatch.HubOption.IsSet)
            {
                writer.WritePropertyName("hub");
                JsonSerializer.Serialize(writer, shipmentBatch.Hub, jsonSerializerOptions);
            }
            if (shipmentBatch.ProgramOption.IsSet)
            {
                writer.WritePropertyName("program");
                JsonSerializer.Serialize(writer, shipmentBatch.Program, jsonSerializerOptions);
            }
            if (shipmentBatch.ShipmentImportStatusesOption.IsSet)
            {
                writer.WritePropertyName("shipmentImportStatuses");
                JsonSerializer.Serialize(writer, shipmentBatch.ShipmentImportStatuses, jsonSerializerOptions);
            }
            if (shipmentBatch.ShipmentsOption.IsSet)
            {
                writer.WritePropertyName("shipments");
                JsonSerializer.Serialize(writer, shipmentBatch.Shipments, jsonSerializerOptions);
            }
            if (shipmentBatch.UploadedOption.IsSet)
                writer.WriteString("uploaded", shipmentBatch.UploadedOption.Value!.Value.ToString(UploadedFormat));

            if (shipmentBatch.StartedOption.IsSet)
                writer.WriteString("started", shipmentBatch.StartedOption.Value!.Value.ToString(StartedFormat));

            if (shipmentBatch.OptimizationStartedOption.IsSet)
                writer.WriteString("optimizationStarted", shipmentBatch.OptimizationStartedOption.Value!.Value.ToString(OptimizationStartedFormat));

            if (shipmentBatch.CompletedOption.IsSet)
                writer.WriteString("completed", shipmentBatch.CompletedOption.Value!.Value.ToString(CompletedFormat));

            if (shipmentBatch.OptimizationCompletedOption.IsSet)
                writer.WriteString("optimizationCompleted", shipmentBatch.OptimizationCompletedOption.Value!.Value.ToString(OptimizationCompletedFormat));

            if (shipmentBatch.SourceOption.IsSet)
                writer.WriteString("source", shipmentBatch.Source);

            if (shipmentBatch.ExternalIdOption.IsSet)
                writer.WriteString("externalId", shipmentBatch.ExternalId);

            if (shipmentBatch.TotalOption.IsSet)
                writer.WriteNumber("total", shipmentBatch.TotalOption.Value!.Value);

            if (shipmentBatch.ProcessedCountOption.IsSet)
                writer.WriteNumber("processedCount", shipmentBatch.ProcessedCountOption.Value!.Value);

            if (shipmentBatch.SuccessCountOption.IsSet)
                writer.WriteNumber("successCount", shipmentBatch.SuccessCountOption.Value!.Value);

            if (shipmentBatch.FailedCountOption.IsSet)
                writer.WriteNumber("failedCount", shipmentBatch.FailedCountOption.Value!.Value);

            if (shipmentBatch.ValidCountOption.IsSet)
                writer.WriteNumber("validCount", shipmentBatch.ValidCountOption.Value!.Value);

            if (shipmentBatch.InvalidCountOption.IsSet)
                writer.WriteNumber("invalidCount", shipmentBatch.InvalidCountOption.Value!.Value);

            if (shipmentBatch.AverageTravelSpeedOption.IsSet)
                writer.WriteNumber("averageTravelSpeed", shipmentBatch.AverageTravelSpeedOption.Value!.Value);

            if (shipmentBatch.MaxSecondsOption.IsSet)
                writer.WriteNumber("maxSeconds", shipmentBatch.MaxSecondsOption.Value!.Value);

            var importStatusRawValue = ShipmentBatch.ImportStatusEnumToJsonValue(shipmentBatch.ImportStatusOption.Value!.Value);
            writer.WriteString("importStatus", importStatusRawValue);
            if (shipmentBatch.TotalRoutesOption.IsSet)
                writer.WriteNumber("totalRoutes", shipmentBatch.TotalRoutesOption.Value!.Value);

            if (shipmentBatch.RoutesCreatedOption.IsSet)
                writer.WriteNumber("routesCreated", shipmentBatch.RoutesCreatedOption.Value!.Value);

            if (shipmentBatch.TotalLegsRequestsOption.IsSet)
                writer.WriteNumber("totalLegsRequests", shipmentBatch.TotalLegsRequestsOption.Value!.Value);

            if (shipmentBatch.LegsRequestedOption.IsSet)
                writer.WriteNumber("legsRequested", shipmentBatch.LegsRequestedOption.Value!.Value);

            if (shipmentBatch.InitScoreOption.IsSet)
                writer.WriteNumber("initScore", shipmentBatch.InitScoreOption.Value!.Value);

            if (shipmentBatch.HardScoreOption.IsSet)
                writer.WriteNumber("hardScore", shipmentBatch.HardScoreOption.Value!.Value);

            if (shipmentBatch.MediumScoreOption.IsSet)
                writer.WriteNumber("mediumScore", shipmentBatch.MediumScoreOption.Value!.Value);

            if (shipmentBatch.SoftScoreOption.IsSet)
                writer.WriteNumber("softScore", shipmentBatch.SoftScoreOption.Value!.Value);
        }
    }
}
